"""
Caddy configuration manager.

Generates Caddyfile content from PlatformConfig and writes it
to a shared volume for the host-side watcher to pick up.
"""
import os
import logging

logger = logging.getLogger(__name__)

# Path inside the container where caddy-config volume is mounted
CADDY_CONFIG_DIR = os.environ.get('CADDY_CONFIG_DIR', '/caddy-config')
CADDY_FILE_PATH = os.path.join(CADDY_CONFIG_DIR, 'Caddyfile')
CADDY_RELOAD_FLAG = os.path.join(CADDY_CONFIG_DIR, '.reload')


def generate_caddyfile(config) -> str:
    """
    Generate Caddyfile content from a PlatformConfig instance.

    Modes:
    - IP-only: simple :80 reverse proxy
    - SSL (no wildcard): domain block with auto HTTPS + :80 fallback
    - SSL + wildcard: domain block + *.domain with Cloudflare DNS challenge
    """
    sections = []
    domain = config.domain.strip() if config.domain else ''
    ip = config.server_ip or ''

    if config.use_ssl and domain:
        # Main domain — auto HTTPS via Let's Encrypt
        sections.append(f"""{domain} {{
    reverse_proxy localhost:8090
    encode gzip
    log {{
        output file /var/log/caddy/access.log
    }}
}}""")

        # Wildcard subdomains for deployed services
        if config.wildcard_subdomains and config.cloudflare_api_token:
            sections.append(f"""*.{domain} {{
    tls {{
        dns cloudflare {{env.CLOUDFLARE_API_TOKEN}}
    }}
    reverse_proxy localhost:8081
}}""")

    elif domain and not config.use_ssl:
        # Domain without SSL (HTTP only)
        sections.append(f"""http://{domain} {{
    reverse_proxy localhost:8090
    encode gzip
}}""")

    else:
        # IP-only mode — plain HTTP
        sections.append(""":80 {
    reverse_proxy localhost:8090
}""")

    # Always add IP fallback if we have a domain (so IP still works)
    if domain and config.use_ssl:
        sections.append(""":80 {
    reverse_proxy localhost:8090
}""")

    header = "# CloudNeuron Caddyfile — Auto-generated by Settings UI\n"
    header += "# Do not edit manually; changes will be overwritten.\n\n"
    return header + "\n\n".join(sections) + "\n"


def apply_caddyfile(content: str) -> dict:
    """
    Write Caddyfile to the shared volume and create a reload flag.
    The host-side watcher script picks up the flag and reloads Caddy.

    Returns a status dict.
    """
    result = {'ok': False, 'message': ''}

    try:
        os.makedirs(CADDY_CONFIG_DIR, exist_ok=True)

        with open(CADDY_FILE_PATH, 'w') as f:
            f.write(content)

        # Create reload flag — the host watcher will pick this up
        with open(CADDY_RELOAD_FLAG, 'w') as f:
            f.write('reload')

        result['ok'] = True
        result['message'] = 'Caddyfile written and reload flag set'
        logger.info("Caddyfile written to %s", CADDY_FILE_PATH)

    except OSError as e:
        result['message'] = f'Failed to write Caddyfile: {e}'
        logger.error("Failed to write Caddyfile: %s", e)

    return result
