"""
Caddy configuration manager.

Generates Caddyfile content from PlatformConfig and writes it
to a shared volume for the host-side watcher to pick up.
"""

import logging
import os

from apps.deployments.domain_utils import normalize_domain

logger = logging.getLogger(__name__)

# Path inside the container where caddy-config volume is mounted
CADDY_CONFIG_DIR = os.environ.get("CADDY_CONFIG_DIR", "/caddy-config")
CADDY_FILE_PATH = os.path.join(CADDY_CONFIG_DIR, "Caddyfile")
CADDY_RELOAD_FLAG = os.path.join(CADDY_CONFIG_DIR, ".reload")


def _build_service_domain_block(domain: str) -> str:
    """Build a Caddy site block for a service domain routed via Traefik."""
    lines = [f"{domain} {{"]
    lines.extend(
        [
            "    reverse_proxy localhost:8081",
            "    encode gzip",
            "    log {",
            "        output file /var/log/caddy/access.log",
            "    }",
            "}",
        ]
    )
    return "\n".join(lines)


def _get_service_domain_blocks() -> list:
    """
    Query all services and generate Caddy blocks for routable app domains.
    Includes both service.public_domain and service.custom_domains.
    """
    blocks = []
    seen = set()
    try:
        from apps.deployments.models import Service

        for service in Service.objects.all():
            all_domains = []
            if isinstance(service.public_domain, str) and service.public_domain.strip():
                all_domains.append(service.public_domain)
            all_domains.extend(service.custom_domains or [])

            for domain in all_domains:
                value = domain.strip() if isinstance(domain, str) else ""
                if not value:
                    continue
                try:
                    value = normalize_domain(value)
                except ValueError:
                    logger.warning(
                        "Skipping invalid domain %r for service %s",
                        domain,
                        service.id,
                    )
                    continue
                if value in seen:
                    continue
                seen.add(value)
                blocks.append(_build_service_domain_block(value))
    except Exception as exc:  # pylint: disable=broad-exception-caught
        logger.warning("Could not load service domains for Caddyfile: %s", exc)
    return blocks


def generate_caddyfile(config) -> str:
    """
    Generate Caddyfile content from a PlatformConfig instance.

    Modes:
    - IP-only: simple :80 reverse proxy
    - SSL (no wildcard): domain block with auto HTTPS + :80 fallback
    - SSL + wildcard: domain block + *.domain with Cloudflare DNS challenge

    Also includes per-service public and custom domain blocks.
    """
    sections = []
    domain = ""
    cloudflare_token = (getattr(config, "cloudflare_api_token", "") or "").strip()

    if config.domain:
        try:
            domain = normalize_domain(config.domain)
        except ValueError:
            logger.warning("Ignoring invalid platform domain in config: %r", config.domain)

    if config.use_ssl and domain:
        # Main domain - auto HTTPS via Let's Encrypt
        sections.append(
            f"""{domain} {{
    reverse_proxy localhost:8090
    encode gzip
    log {{
        output file /var/log/caddy/access.log
    }}
}}"""
        )

        # Wildcard subdomains for deployed services
        if config.wildcard_subdomains and cloudflare_token:
            sections.append(
                f"""*.{domain} {{
    tls {{
        dns cloudflare {cloudflare_token}
    }}
    reverse_proxy localhost:8081
}}"""
            )

    elif domain and not config.use_ssl:
        # Domain without SSL (HTTP only)
        sections.append(
            f"""http://{domain} {{
    reverse_proxy localhost:8090
    encode gzip
}}"""
        )

    else:
        # IP-only mode - plain HTTP
        sections.append(
            """:80 {
    reverse_proxy localhost:8090
}"""
        )

    # Always add IP fallback if we have a domain (so IP still works)
    if domain and config.use_ssl:
        sections.append(
            """:80 {
    reverse_proxy localhost:8090
}"""
        )

    # Per-service domains (public + custom) routed to Traefik.
    # Do not force DNS challenge here; many custom domains are not in our
    # Cloudflare account, so HTTP-01/TLS-ALPN must remain available.
    service_blocks = _get_service_domain_blocks()
    sections.extend(service_blocks)

    header = "# CloudNeuron Caddyfile - Auto-generated by Settings UI\n"
    header += "# Do not edit manually; changes will be overwritten.\n\n"
    return header + "\n\n".join(sections) + "\n"


def apply_caddyfile(content: str) -> dict:
    """
    Write Caddyfile to the shared volume and create a reload flag.
    The host-side watcher script picks up the flag and reloads Caddy.

    Returns a status dict.
    """
    result = {"ok": False, "message": ""}

    try:
        os.makedirs(CADDY_CONFIG_DIR, exist_ok=True)

        with open(CADDY_FILE_PATH, "w", encoding="utf-8") as handle:
            handle.write(content)

        # Create reload flag - the host watcher will pick this up
        with open(CADDY_RELOAD_FLAG, "w", encoding="utf-8") as handle:
            handle.write("reload")

        result["ok"] = True
        result["message"] = "Caddyfile written and reload flag set"
        logger.info("Caddyfile written to %s", CADDY_FILE_PATH)

    except OSError as exc:
        result["message"] = f"Failed to write Caddyfile: {exc}"
        logger.error("Failed to write Caddyfile: %s", exc)

    return result
