# Generated by Django 5.0.14 on 2026-02-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_key", models.TextField(blank=True, default="")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("community", "Community"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="community",
                        max_length=20,
                    ),
                ),
                ("license_data", models.TextField(blank=True, default="")),
                ("is_valid", models.BooleanField(default=False)),
                ("last_validated", models.DateTimeField(blank=True, null=True)),
                ("validation_error", models.TextField(blank=True, default="")),
                (
                    "licensed_to",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "instance_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_services", models.IntegerField(default=3)),
                ("max_team_members", models.IntegerField(default=1)),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stripe", "Stripe"),
                            ("paystack", "Paystack"),
                            ("nowpayments", "NowPayments"),
                            ("paypal", "PayPal"),
                            ("manual", "Manual"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform License",
            },
        ),
    ]
