agent {
  trust_domain = "ecosystem.local"
  server_address = "spire-server-ecosystem"
  server_port = "8081"
  socket_path = "/opt/spire/run/agent.sock"
  log_level = "INFO"
  insecure_bootstrap = true
}

plugins {
  NodeAttestor "join_token" {
    plugin_data {}
  }
  KeyManager "disk" {
    plugin_data { directory = "/opt/spire/data" }
  }
  WorkloadAttestor "unix" {
    plugin_data { discover_workload_path = true }
  }
  WorkloadAttestor "docker" {
    plugin_data { docker_host = "tcp://traefik-socket-proxy:2375" }
  }
}

health_checks {
  listener_enabled = true
  bind_port = "8082"
  live_path = "/live"
  ready_path = "/ready"
}
