server {
  bind_address = "0.0.0.0"
  bind_port = "8081"
  trust_domain = "ecosystem.local"
  data_dir = "/opt/spire/data"
  log_level = "INFO"
  ca_key_type = "ec-p256"
  default_x509_svid_ttl = "1h"
  ca_subject {
    country = ["US"]
    organization = ["Smsly"]
    common_name = ""
  }
}

plugins {
  DataStore "sql" {
    plugin_data {
      database_type = "sqlite3"
      connection_string = "/opt/spire/data/datastore.sqlite3"
    }
  }

  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "disk" {
    plugin_data {
      keys_path = "/opt/spire/data/keys.json"
      cert_path = "/opt/spire/data/cert.pem"
    }
  }


}

health_checks {
  listener_enabled = true
  bind_port = "8080"
  bind_address = "0.0.0.0"
  live_path = "/live"
  ready_path = "/ready"
}
