# Generated by Django 5.0.14 on 2026-02-25 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0029_platformupdate"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="WARNING",
                        max_length=20,
                    ),
                ),
                ("metric", models.CharField(max_length=50)),
                ("threshold", models.FloatField()),
                ("current_value", models.FloatField()),
                ("message", models.TextField()),
                ("acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_alerts",
                        to="deployments.service",
                    ),
                ),
            ],
        ),
    ]
