# Generated by Django 5.0.14 on 2026-07-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alert_rules_and_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('deploy_success', 'Deploy Success'), ('deploy_failed', 'Deploy Failed'), ('health_alert', 'Health Alert'), ('billing_due', 'Billing Due'), ('ssl_expiring', 'SSL Expiring'), ('backup_completed', 'Backup Completed'), ('replication_lag', 'Replication Lag'), ('replication_node_down', 'Replication Node Down')], max_length=50),
        ),
    ]
