# Generated by Django 5.0.14 on 2026-06-18 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_add_organizations_and_sso'),
        ('teams', '0004_alter_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization this team belongs to. If null, the team is personal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='organizations.organization'),
        ),
    ]
