# Generated by Django 5.0.14 on 2026-06-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_add_organizations_and_sso'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='can_manage_billing',
            field=models.BooleanField(default=False, help_text='Allow this team member to manage billing (plans, checkout, invoices)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, membership automatically expires after this date', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Suspend membership without removing the record'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Custom permission code overrides for this member. If set, these replace the default role permissions.'),
        ),
    ]
