# Generated by Django 5.0.14 on 2026-07-19 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("deployments", "0155_remove_apitoken_user_remove_auditlog_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label, e.g. 'My Laptop CLI'",
                        max_length=100,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 8 chars of the token for lookup",
                        max_length=12,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the full token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Token",
                "db_table": "deployments_apitoken",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "delivery_id",
                    models.CharField(
                        help_text="Provider-supplied unique delivery identifier (e.g. X-GitHub-Delivery).",
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="github",
                        help_text="Webhook provider that produced this delivery.",
                        max_length=32,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Event type from the provider (push, pull_request, etc.).",
                        max_length=64,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="processed",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "deployments_webhookdelivery",
                "indexes": [
                    models.Index(
                        fields=["provider", "received_at"],
                        name="deployments_provide_1b4d19_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("actor", models.CharField(default="system", max_length=255)),
                ("action", models.CharField(default="unknown", max_length=255)),
                ("target", models.CharField(default="none", max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "previous_hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deployments.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deployments_auditlog",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["hash"], name="deployments_hash_fe5aec_idx"),
                    models.Index(fields=["actor"], name="deployments_actor_0cbddc_idx"),
                ],
            },
        ),
    ]
