# Generated by Django 5.0.14 on 2026-10-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apitoken_webhookdelivery_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text="Permission scopes, e.g. ['read'] or ['read', 'write']. Empty = full access (legacy)."),
        ),
    ]
