"""0001 Initial module."""
# Generated by Django 5.0.14 on 2026-01-30 13:19

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for this integration",
                        max_length=255,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Services"),
                            ("GCP", "Google Cloud Platform"),
                            ("AZURE", "Microsoft Azure"),
                            ("RAILWAY", "Railway"),
                            ("VERCEL", "Vercel"),
                            ("LOCAL", "Local / K3s"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="AWS Access Key / GCP Service Account Key (JSON)",
                        null=True,
                    ),
                ),
                (
                    "api_secret",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, help_text="AWS Secret Key / Private Key", null=True
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True,
                        help_text="GCP/Azure Project/Subscription ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        help_text="Azure Tenant ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        default="us-east-1",
                        help_text="Default region for resources",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CloudResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        help_text="Provider-specific ID (ARN, SelfLink, etc)",
                        max_length=255,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="e.g., AWS::S3::Bucket, Microsoft.Web/sites",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(default="PROVISIONING", max_length=50)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional properties (tags, specific config)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="cloud.cloudprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IAMRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "arn",
                    models.CharField(
                        blank=True,
                        help_text="Amazon Resource Name or equivalent",
                        max_length=512,
                    ),
                ),
                (
                    "policy_document",
                    models.JSONField(
                        default=dict, help_text="IAM Policy JSON"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iam_roles",
                        to="cloud.cloudprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("arn", models.CharField(blank=True, max_length=512)),
                ("version_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="cloud.cloudprovider",
                    ),
                ),
            ],
        ),
    ]
