# Generated by Django 4.2.28 on 2026-05-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudprovider',
            name='provider_type',
            field=models.CharField(choices=[('AWS', 'Amazon Web Services'), ('GCP', 'Google Cloud Platform'), ('AZURE', 'Microsoft Azure'), ('RAILWAY', 'Railway'), ('VERCEL', 'Vercel'), ('LOCAL', 'Local / K3s'), ('REMOTE', 'Remote Node')], max_length=20),
        ),
    ]
