# Generated by Django 5.0.14 on 2026-07-19 14:55

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0002_alter_cloudprovider_provider_type"),
        ("deployments", "0154_service_autoscale_enabled"),
        ("organizations", "0002_organizationmembership_can_manage_billing_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupEncryptionKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        db_index=True,
                        help_text="4 random bytes as 8-char hex; matches the V2 backup header key_id.",
                        max_length=8,
                        unique=True,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="First 4 bytes of SHA-256(raw_key) as 8-char hex; matches V2 header fingerprint.",
                        max_length=8,
                    ),
                ),
                (
                    "key_material_encrypted",
                    encrypted_model_fields.fields.EncryptedCharField(
                        help_text="Fernet BACKUP_ENCRYPTION_KEY, encrypted at rest with FIELD_ENCRYPTION_KEY."
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Operator label e.g. "master-a-imported-2026-06-14".',
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto-generated by this master"),
                            ("IMPORTED", "Imported from another master"),
                        ],
                        default="AUTO",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True for the row matching the current BACKUP_ENCRYPTION_KEY env var.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "deployments_backupencryptionkey",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["fingerprint", "is_active"],
                        name="deployments_fingerp_107a94_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BackupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_server_wide", models.BooleanField(default=False)),
                ("db_only", models.BooleanField(default=False)),
                (
                    "cron_expression",
                    models.CharField(default="0 3 * * *", max_length=100),
                ),
                ("retention_days", models.IntegerField(default=7)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(null=True)),
                ("next_run", models.DateTimeField(null=True)),
                (
                    "cloud_upload_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When True, automatically upload backups to the configured cloud destination. Turn off to keep backups local-only even with credentials set.",
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("local", "Local"), ("s3", "S3 / R2 / MinIO")],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("s3_bucket", models.CharField(blank=True, default="", max_length=255)),
                (
                    "s3_region",
                    models.CharField(blank=True, default="us-east-1", max_length=100),
                ),
                (
                    "s3_endpoint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom endpoint for R2/MinIO. Leave blank for AWS S3.",
                        max_length=500,
                    ),
                ),
                (
                    "s3_access_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "s3_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_backupschedule",
            },
        ),
        migrations.CreateModel(
            name="CloudStorageDestination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("r2", "Cloudflare R2"),
                            ("s3", "Amazon S3"),
                            ("minio", "MinIO / Self-Hosted S3"),
                            ("b2", "Backblaze B2 (S3-compatible)"),
                            ("digitalocean", "DigitalOcean Spaces"),
                            ("vps", "Custom Storage VPS"),
                            ("wasabi", "Wasabi Hot Storage"),
                        ],
                        default="s3",
                        max_length=30,
                    ),
                ),
                ("bucket", models.CharField(max_length=255)),
                ("region", models.CharField(default="us-east-1", max_length=100)),
                (
                    "endpoint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom endpoint for R2/MinIO/B2. Leave blank for AWS S3.",
                        max_length=500,
                    ),
                ),
                ("access_key", encrypted_model_fields.fields.EncryptedCharField()),
                ("secret_key", encrypted_model_fields.fields.EncryptedCharField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = platform-wide; set = per-service only",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloud_destinations",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_cloudstoragedestination",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServerBackup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable label for quick identification",
                        max_length=255,
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("db_only", models.BooleanField(default=False)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("services_included", models.JSONField(default=list)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata: cloud_upload_error, checksums, etc.",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cloud_uploaded", models.BooleanField(default=False)),
                (
                    "cloud_bucket",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cloud_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="S3 object key, e.g. smsly-backups/<scope>/<filename>",
                        max_length=1024,
                    ),
                ),
                (
                    "cloud_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cloud.cloudstoragedestination",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_serverbackup",
            },
        ),
        migrations.CreateModel(
            name="ServiceBackup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Human-readable label for quick identification, e.g. "Pre-upgrade backup" or "Cloud restore"',
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("db_only", models.BooleanField(default=False)),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("SCHEDULED", "Scheduled"),
                            ("PRE_TRANSFER", "Pre-Transfer"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cloud_uploaded", models.BooleanField(default=False)),
                (
                    "cloud_bucket",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cloud_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="S3 object key, e.g. smsly-backups/<service>/<filename>",
                        max_length=1024,
                    ),
                ),
                (
                    "cloud_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cloud.cloudstoragedestination",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_servicebackup",
            },
        ),
        migrations.CreateModel(
            name="SnapshotSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_server_wide", models.BooleanField(default=False)),
                (
                    "cron_expression",
                    models.CharField(default="0 3 * * *", max_length=100),
                ),
                ("retention_days", models.IntegerField(default=7)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(null=True)),
                ("next_run", models.DateTimeField(null=True)),
                (
                    "cloud_upload_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When True, automatically upload snapshots to the configured cloud destination. Turn off to keep snapshots local-only even with credentials set.",
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("local", "Local"), ("s3", "S3 / R2 / MinIO")],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("s3_bucket", models.CharField(blank=True, default="", max_length=255)),
                (
                    "s3_region",
                    models.CharField(blank=True, default="us-east-1", max_length=100),
                ),
                (
                    "s3_endpoint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom endpoint for R2/MinIO. Leave blank for AWS S3.",
                        max_length=500,
                    ),
                ),
                (
                    "s3_access_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "s3_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_schedules",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_snapshotschedule",
            },
        ),
        migrations.CreateModel(
            name="GitHubAppInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("account_login", models.CharField(max_length=255)),
                ("account_id", models.BigIntegerField()),
                (
                    "account_type",
                    models.CharField(
                        choices=[("User", "User"), ("Organization", "Organization")],
                        max_length=20,
                    ),
                ),
                ("account_avatar_url", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "repository_selection",
                    models.CharField(default="selected", max_length=20),
                ),
                ("repositories", models.JSONField(blank=True, default=list)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("events", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_app_installations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="github_app_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deployments_githubappinstallation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="deployments_user_id_0ad2ba_idx"
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="deployments_organiz_0df9ec_idx",
                    ),
                    models.Index(
                        fields=["account_login"], name="deployments_account_270407_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Optional human label e.g. "before Redis upgrade"',
                        max_length=255,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("PRE_DEPLOY", "Pre-Deploy"),
                            ("PRE_ENV_CHANGE", "Pre-Env Change"),
                            ("SCHEDULED", "Scheduled"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "config_data",
                    models.JSONField(
                        default=dict,
                        help_text="Full config payload: env_vars, deploy_type, docker_image, repository_url, branch, public_domain, resources, replicas, addons, build/start commands, health check, etc.",
                    ),
                ),
                (
                    "diff_summary",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Computed diff from parent snapshot (added/removed/changed keys).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cloud_uploaded", models.BooleanField(default=False)),
                (
                    "cloud_bucket",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cloud_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="S3 object key, e.g. smsly-snapshots/<service>/<filename>",
                        max_length=1024,
                    ),
                ),
                (
                    "cloud_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cloud.cloudstoragedestination",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_snapshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous snapshot in the diff chain.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cloud.servicesnapshot",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "db_table": "deployments_servicesnapshot",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service", "-created_at"],
                        name="deployments_service_bf4bea_idx",
                    )
                ],
            },
        ),
    ]
