# Generated by Django 5.0.14 on 2026-08-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_add_backup_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudprovider',
            name='provider_type',
            field=models.CharField(choices=[('AWS', 'Amazon Web Services'), ('GCP', 'Google Cloud Platform'), ('AZURE', 'Microsoft Azure'), ('HETZNER', 'Hetzner Cloud'), ('UPCLOUD', 'UpCloud'), ('DIGITALOCEAN', 'DigitalOcean'), ('RAILWAY', 'Railway'), ('VERCEL', 'Vercel'), ('LOCAL', 'Local / K3s'), ('REMOTE', 'Remote Node')], max_length=20),
        ),
    ]
