# Generated by Django 5.0.14 on 2026-09-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_backup_restore_bookkeeping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudprovider',
            name='scope',
            field=models.CharField(blank=True, default='platform', help_text="Tenant scope: 'platform' (default), 'ecosystem', or custom.", max_length=32),
        ),
        migrations.AlterField(
            model_name='serverbackup',
            name='backup_type',
            field=models.CharField(choices=[('SERVER', 'Server'), ('SERVER_TRANSFER', 'Server Transfer')], default='SERVER', max_length=20),
        ),
        migrations.AlterField(
            model_name='serverbackup',
            name='restore_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serverbackup',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebackup',
            name='restore_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicebackup',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
