{
 "title": "Freebox",
 "description": "Dashboard pour le monitoring de sa Freebox Delta S. \n\nTuto monitoring freebox : https://www.nas-forum.com/forum/topic/66394-tuto-monitorer-sa-freebox-revolution/",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Débits Synchro",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tag2" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 8" ], "type": "math" },
       { "params": [ "real" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "box" }
     ]
    }
   ]
  },
  {
   "title": "Trafic Total",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tag2" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "box" }
     ]
    }
   ]
  },
  {
   "title": "Status Signal Fibre Addr",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sfp_has_signal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Signal" ], "type": "alias" }
      ],
      [
       { "params": [ "ipv4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IPv4" ], "type": "alias" }
      ],
      [
       { "params": [ "ipv6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IPv6" ], "type": "alias" }
      ],
      [
       { "params": [ "media" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Media" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "box" }
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "pretty_name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "firmware_version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Dowload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "box" },
      { "condition": "AND", "key": "tag2", "operator": "=", "value": "down" }
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Dowload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "box" },
      { "condition": "AND", "key": "tag2", "operator": "=", "value": "up" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU Master",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Master" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag3", "operator": "=", "value": "temp_cpu_cp_master" }
     ]
    },
    {
     "alias": "CPU Slave",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Slave" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag3", "operator": "=", "value": "temp_cpu_cp_slave" }
     ]
    },
    {
     "alias": "CPU AP",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "AP" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag3", "operator": "=", "value": "temp_cpu_ap" }
     ]
    },
    {
     "alias": "Sensor 1",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Sensor 1" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag3", "operator": "=", "value": "temp_t1" }
     ]
    },
    {
     "alias": "Sensor 2",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Sensor 2" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag3", "operator": "=", "value": "temp_t2" }
     ]
    },
    {
     "alias": "Sensor 3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Sensor 3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag3", "operator": "=", "value": "temp_t3" }
     ]
    }
   ]
  },
  {
   "title": "Disque Freebox",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 5 },
   "targets": [
    {
     "measurement": "freebox",
     "query": "SELECT last(\"firmware\") AS \"Firmware\", last(\"model\") AS \"Model\", last(\"serial\") AS \"Serial nb\", last(\"temp\") AS \"Temp\", last(\"total_bytes\") AS \"Taille disque\", last(\"used_bytes\") AS \"Utilisé\" FROM \"freebox\" WHERE (\"tag1\" = 'Disque') AND $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial nb" ], "type": "alias" }
      ],
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp" ], "type": "alias" }
      ],
      [
       { "params": [ "total_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Taille disque" ], "type": "alias" }
      ],
      [
       { "params": [ "free_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Utilisé" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "dd-1" }
     ]
    },
    {
     "measurement": "freebox",
     "query": "SELECT last(\"firmware\") AS \"Firmware\", last(\"model\") AS \"Model\", last(\"serial\") AS \"Serial nb\", last(\"temp\") AS \"Temp\", last(\"total_bytes\") AS \"Taille disque\", last(\"used_bytes\") AS \"Utilisé\", last(\"spinning\") AS \"Spinning\" FROM \"freebox\" WHERE (\"tag2\" = 'dd-2') AND $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial nb" ], "type": "alias" }
      ],
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp" ], "type": "alias" }
      ],
      [
       { "params": [ "total_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Taille disque" ], "type": "alias" }
      ],
      [
       { "params": [ "free_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Utilisé" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "dd-2" }
     ]
    },
    {
     "measurement": "freebox",
     "query": "SELECT last(\"firmware\") AS \"Firmware\", last(\"model\") AS \"Model\", last(\"serial\") AS \"Serial nb\", last(\"temp\") AS \"Temp\", last(\"total_bytes\") AS \"Taille disque\", last(\"free_bytes\") AS \"Utilisé\", last(\"spinning\") AS \"Spinning\" FROM \"freebox\" WHERE (\"tag2\" = 'dd-3') AND $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial nb" ], "type": "alias" }
      ],
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp" ], "type": "alias" }
      ],
      [
       { "params": [ "total_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Taille disque" ], "type": "alias" }
      ],
      [
       { "params": [ "free_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Utilisé" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "dd-3" }
     ]
    },
    {
     "measurement": "freebox",
     "query": "SELECT last(\"firmware\") AS \"Firmware\", last(\"model\") AS \"Model\", last(\"serial\") AS \"Serial nb\", last(\"temp\") AS \"Temp\", last(\"total_bytes\") AS \"Taille disque\", last(\"used_bytes\") AS \"Utilisé\", last(\"spinning\") AS \"Spinning\" FROM \"freebox\" WHERE (\"tag2\" = 'dd-2') AND $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial nb" ], "type": "alias" }
      ],
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp" ], "type": "alias" }
      ],
      [
       { "params": [ "total_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Taille disque" ], "type": "alias" }
      ],
      [
       { "params": [ "free_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Utilisé" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "dd-4" }
     ]
    }
   ]
  },
  {
   "title": "Freebox Up time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "System Fan",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "Fan" }
     ]
    }
   ]
  },
  {
   "title": "Switch Ports Mode",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tag2" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "Etat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "Switch" }
     ]
    }
   ]
  },
  {
   "title": "Stations Wifi",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "tag3" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "primary_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "wifi_list" }
     ]
    }
   ]
  },
  {
   "title": "Switch Freebox",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col : $tag_tag1",
     "groupBy": [
      { "params": [ "tag1" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "query": "SELECT \"bytes_rate\" *8/-1 AS \"Rx\" FROM \"freebox\" WHERE (\"tag2\" = 'Rx') AND $timeFilter GROUP BY \"tag1\"",
     "select": [
      [
       { "params": [ "bytes_rate" ], "type": "field" },
       { "params": [ "Rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "Rx" },
      { "condition": "AND", "key": "tag1", "operator": "!=", "value": "Port#9999" }
     ]
    },
    {
     "alias": "$col : $tag_tag1",
     "groupBy": [
      { "params": [ "tag1" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "bytes_rate" ], "type": "field" },
       { "params": [ "/-1" ], "type": "math" },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "Tx" },
      { "condition": "AND", "key": "tag1", "operator": "!=", "value": "Port#9999" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Freebox",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col : $tag_tag2",
     "groupBy": [
      { "params": [ "tag2" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "tx_rate" ], "type": "field" },
       { "params": [ "/-1" ], "type": "math" },
       { "params": [ "TX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "wifi_list" }
     ]
    },
    {
     "alias": "$col : $tag_tag2",
     "groupBy": [
      { "params": [ "tag2" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "rx_rate" ], "type": "field" },
       { "params": [ "RX" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag1", "operator": "=", "value": "wifi_list" }
     ]
    }
   ]
  },
  {
   "title": "Freebox Port Fibre",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "tag2" ], "type": "tag" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       { "params": [ "Freebox  Fibre" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "up" }
     ]
    },
    {
     "alias": "Download",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       { "params": [ " / -1" ], "type": "math" },
       { "params": [ "Freebox  Fibre" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "tag2", "operator": "=", "value": "down" }
     ]
    }
   ]
  }
 ]
}