# Generated by Django 5.0.14 on 2026-02-13 00:00

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIProviderSettings",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                (
                    "active_provider",
                    models.CharField(
                        choices=[("mock", "Mock"), ("openai", "OpenAI"), ("grok", "Grok"), ("gemini", "Gemini")],
                        default="mock",
                        max_length=20,
                    ),
                ),
                ("openai_api_key", encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ("openai_model", models.CharField(blank=True, default="gpt-4o-mini", max_length=100)),
                ("grok_api_key", encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ("grok_model", models.CharField(blank=True, default="grok-3-mini", max_length=100)),
                ("gemini_api_key", encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ("gemini_model", models.CharField(blank=True, default="gemini-2.0-flash", max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

