# Generated by Django 5.0.14 on 2026-02-15 00:00

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiprovidersettings",
            name="active_provider",
        ),
        migrations.AddField(
            model_name="aiprovidersettings",
            name="claude_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiprovidersettings",
            name="claude_model",
            field=models.CharField(blank=True, default="claude-sonnet-4-20250514", max_length=100),
        ),
    ]

