# Generated by Django 5.0.14 on 2026-02-27 00:00

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0002_remove_aiprovidersettings_active_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprovidersettings",
            name="jules_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiprovidersettings",
            name="jules_model",
            field=models.CharField(blank=True, default="jules-latest", max_length=100),
        ),
    ]
