# Generated by Django 5.0.14 on 2026-02-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0003_aiprovidersettings_jules_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprovidersettings",
            name="ecosystem_wave_recheck_seconds",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Seconds between dependency-wave status checks",
            ),
        ),
        migrations.AddField(
            model_name="aiprovidersettings",
            name="ecosystem_wave_size",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Maximum services deployed concurrently per dependency wave",
            ),
        ),
        migrations.AddField(
            model_name="aiprovidersettings",
            name="jules_base_url",
            field=models.CharField(
                blank=True,
                default="https://api.jules.google.com/v1",
                help_text="OpenAI-compatible base URL for Jules provider",
                max_length=255,
            ),
        ),
    ]
