# Generated by Django 4.2.28 on 2026-03-11 19:36

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_aiprovidersettings_orchestration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='deepseek_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='deepseek_model',
            field=models.CharField(blank=True, default='deepseek-coder', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='localllm_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='localllm_base_url',
            field=models.CharField(blank=True, default='http://localhost:11434/v1', help_text='OpenAI-compatible base URL for local LLM (e.g. Ollama, vLLM)', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='localllm_model',
            field=models.CharField(blank=True, default='local-model', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='senate_enabled',
            field=models.BooleanField(default=True, help_text='Enable collaborative deliberation (Senate Committee) when 2+ providers configured'),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='senate_max_members',
            field=models.PositiveSmallIntegerField(default=5, help_text='Maximum number of AI members allowed in a Senate Committee'),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='smslycloud_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='smslycloud_model',
            field=models.CharField(blank=True, default='smsly-latest', max_length=100),
        ),
    ]
