# Generated by Django 4.2.28 on 2026-05-07 08:06

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_aiprovidersettings_deepseek_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='alibaba_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='alibaba_model',
            field=models.CharField(blank=True, default='qwen-max', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='groq_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='groq_model',
            field=models.CharField(blank=True, default='llama-3.3-70b-versatile', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='openrouter_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='openrouter_model',
            field=models.CharField(blank=True, default='openrouter/auto', max_length=100),
        ),
    ]
