# Generated by Django 4.2.28 on 2026-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0006_aiprovidersettings_alibaba_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='jules_auto_deploy_pr',
            field=models.BooleanField(default=True, help_text='Automatically redeploy services from the branch of Jules auto-fix PRs'),
        ),
    ]
