# Generated by Django 4.2.28 on 2026-05-23 00:00

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0007_aiprovidersettings_jules_auto_deploy_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='freemodel_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='freemodel_base_url',
            field=models.CharField(blank=True, default='https://api.freemodel.dev/v1', help_text='OpenAI-compatible base URL for FreeModel.dev provider', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='freemodel_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='opencode_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='opencode_base_url',
            field=models.CharField(blank=True, default='https://api.opencode.ai/v1', help_text='OpenAI-compatible base URL for OpenCode API provider', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='opencode_model',
            field=models.CharField(blank=True, default='opencode-latest', max_length=100),
        ),
    ]
