# Generated by Django 4.2.28 on 2026-05-23 00:00

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0008_aiprovidersettings_freemodel_and_opencode'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='mistral_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='mistral_base_url',
            field=models.CharField(blank=True, default='https://api.mistral.ai/v1', help_text='OpenAI-compatible base URL for Mistral provider', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='mistral_model',
            field=models.CharField(blank=True, default='mistral-small-latest', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='nvidia_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='nvidia_base_url',
            field=models.CharField(blank=True, default='https://integrate.api.nvidia.com/v1', help_text='OpenAI-compatible base URL for NVIDIA NIM provider', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='nvidia_model',
            field=models.CharField(blank=True, default='nvidia/llama-3.1-nemotron-70b-instruct', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='cloudflare_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='cloudflare_base_url',
            field=models.CharField(blank=True, default='https://gateway.ai.cloudflare.com/v1/YOUR_ACCOUNT_ID/default/workers-ai', help_text='Cloudflare AI Gateway URL. Replace YOUR_ACCOUNT_ID with your Cloudflare account ID.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='cloudflare_model',
            field=models.CharField(blank=True, default='@cf/meta/llama-3.1-8b-instruct', max_length=100),
        ),
    ]
