# Generated by Django 5.0.14 on 2026-06-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0010_llmusage_useraicap_and_jules_default'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='llmusage',
            new_name='intelligenc_user_id_5ba2ae_idx',
            old_name='intelligence_user_id_39e0a9_idx',
        ),
    ]
