# Generated by Django 5.0.14 on 2026-08-15 21:49

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0011_rename_intelligence_user_id_39e0a9_idx_intelligenc_user_id_5ba2ae_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='agentrouter_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='agentrouter_base_url',
            field=models.CharField(blank=True, default='', help_text='OpenAI-compatible base URL for Agent Router provider', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='agentrouter_model',
            field=models.CharField(blank=True, default='agentrouter/auto', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='kimi_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='kimi_base_url',
            field=models.CharField(blank=True, default='https://api.moonshot.ai/v1', help_text='OpenAI-compatible base URL for Kimi (Moonshot) provider', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='kimi_model',
            field=models.CharField(blank=True, default='kimi-latest', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='orcarouter_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='orcarouter_base_url',
            field=models.CharField(blank=True, default='', help_text='OpenAI-compatible base URL for Orca Router provider', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='orcarouter_model',
            field=models.CharField(blank=True, default='orcarouter/auto', max_length=100),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='zenmax_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='zenmax_base_url',
            field=models.CharField(blank=True, default='', help_text='OpenAI-compatible base URL for ZenMax provider', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='zenmax_model',
            field=models.CharField(blank=True, default='zenmax/auto', max_length=100),
        ),
    ]
