{{- range $name := list "backend" "frontend" "celery" }}
{{- if eq (index $.Values $name).serviceAccount.create true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smsly.fullname" $ }}-{{ $name }}
  labels:
    {{- include "smsly.labels" $ | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
