"""Tests for the CoreDNS mesh-DNS zone generation (services.mesh_dns)."""

import os

import django
from django.test import TestCase

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()


class MeshDnsUnitTests(TestCase):
    def test_sanitize_label(self):
        from apps.deployments.services.mesh_dns import _sanitize_label

        self.assertEqual(_sanitize_label("My-Node_01"), "my-node-01")
        self.assertEqual(_sanitize_label("UPPER .. name!!"), "upper-name")
        self.assertEqual(_sanitize_label(""), "node")
        self.assertEqual(_sanitize_label("---"), "node")

    def test_domain_priority_env(self):
        import apps.deployments.services.mesh_dns as mesh_dns

        prev = os.environ.get("MESH_DNS_DOMAIN")
        os.environ["MESH_DNS_DOMAIN"] = "Custom.Search"
        try:
            self.assertEqual(mesh_dns.mesh_dns_domain(), "custom.search")
        finally:
            if prev is None:
                os.environ.pop("MESH_DNS_DOMAIN", None)
            else:
                os.environ["MESH_DNS_DOMAIN"] = prev

    def test_domain_default(self):
        import apps.deployments.services.mesh_dns as mesh_dns

        prev = os.environ.pop("MESH_DNS_DOMAIN", None)
        try:
            self.assertEqual(mesh_dns.mesh_dns_domain(), mesh_dns.DEFAULT_MESH_DNS_DOMAIN)
        finally:
            if prev is not None:
                os.environ["MESH_DNS_DOMAIN"] = prev

    def test_corefile_structure(self):
        from apps.deployments.services.mesh_dns import build_corefile

        corefile = build_corefile()
        self.assertIn(".:53", corefile)
        self.assertIn("hosts /etc/coredns/mesh.hosts", corefile)
        self.assertIn("fallthrough", corefile)
        self.assertIn("forward . /etc/resolv.conf", corefile)
        self.assertIn("loop", corefile)
        self.assertIn("reload", corefile)
        self.assertIn("health :8080", corefile)
        self.assertIn("reload 5s", corefile)

    def test_zone_records_structured(self):
        from apps.deployments.models.mesh import MeshNetwork, WireGuardPeer
        from apps.deployments.services.mesh_dns import get_mesh_zone_records

        mesh = MeshNetwork.objects.create(
            name="default", subnet="10.100.0.0/24", is_active=True,
        )
        MeshNetwork.objects.exclude(id=mesh.id).delete()
        WireGuardPeer.objects.create(
            mesh=mesh, wg_address="10.100.0.1", private_key="", public_key="x" * 44,
            is_active=True, is_local=True, allowed_ips="10.100.0.1/32",
        )
        domain, records = get_mesh_zone_records()
        self.assertEqual(domain, "mesh.internal")
        names = {record["name"] for record in records}
        self.assertIn("master.mesh.internal", names)
        self.assertIn("registry.mesh.internal", names)
        self.assertTrue(all(set(record.keys()) == {"name", "ip"} for record in records))

    def test_empty_zone_still_renders(self):
        import apps.deployments.services.mesh_dns as mesh_dns

        # No mesh rows in a fresh test DB: the file must still render
        # (comment header only) so CoreDNS never fails to parse it.
        content, count = mesh_dns.build_mesh_hosts()
        self.assertIsInstance(content, str)
        self.assertTrue(content.startswith("# Generated by"))
        self.assertTrue(content.endswith("\n"))
        self.assertEqual(count, 0)

    def test_zone_with_mesh_rows(self):
        from apps.deployments.models.mesh import MeshNetwork, WireGuardPeer
        from apps.deployments.services.mesh_dns import build_mesh_hosts

        mesh = MeshNetwork.objects.create(
            name="default", subnet="10.100.0.0/24", is_active=True,
        )
        MeshNetwork.objects.exclude(id=mesh.id).delete()
        master = WireGuardPeer.objects.create(
            mesh=mesh, wg_address="10.100.0.1", private_key="", public_key="x" * 44,
            is_active=True, is_local=True, allowed_ips="10.100.0.1/32",
        )
        node = WireGuardPeer.objects.create(
            mesh=mesh, wg_address="10.100.0.2", private_key="", public_key="y" * 44,
            is_active=True, is_local=False, allowed_ips="10.100.0.2/32",
        )
        _ = (master, node)
        content, count = build_mesh_hosts()

        self.assertIn("10.100.0.1 master.mesh.internal", content)
        self.assertIn("10.100.0.1 registry.mesh.internal", content)
        self.assertIn("10.100.0.1 postgres.mesh.internal", content)
        self.assertIn("10.100.0.1 redis.mesh.internal", content)
        self.assertIn("10.100.0.1 rabbitmq.mesh.internal", content)
        self.assertIn("10.100.0.2 ", content)
        self.assertEqual(count, len([ln for ln in content.splitlines() if not ln.startswith("#")]))
        # Deterministic ordering: same input twice, byte-identical output.
        content2, _ = build_mesh_hosts()
        self.assertEqual(content, content2)

    def test_zone_node_name_label(self):
        from django.contrib.auth import get_user_model

        from apps.deployments.models.core import ManagedServer
        from apps.deployments.models.mesh import MeshNetwork, WireGuardPeer
        from apps.deployments.services.mesh_dns import build_mesh_hosts

        user = get_user_model().objects.create_user("meshdns", "m@t.com", "pass")
        mesh = MeshNetwork.objects.create(
            name="default", subnet="10.100.0.0/24", is_active=True,
        )
        MeshNetwork.objects.exclude(id=mesh.id).delete()
        server = ManagedServer.objects.create(
            name="Worker Node 2!", host="203.0.113.9", node_number=2,
            status="ACTIVE", owner=user,
        )
        WireGuardPeer.objects.create(
            mesh=mesh, server=server, wg_address="10.100.0.2",
            private_key="", public_key="z" * 44, is_active=True, is_local=False,
            allowed_ips="10.100.0.2/32",
        )
        content, _ = build_mesh_hosts()
        self.assertIn("10.100.0.2 grid2.mesh.internal", content)
        self.assertIn("10.100.0.2 worker-node-2.mesh.internal", content)

    def test_apply_is_idempotent(self):
        import tempfile

        import apps.deployments.services.mesh_dns as mesh_dns

        with tempfile.TemporaryDirectory() as tmp:
            mesh_dns.COREDNS_CONFIG_DIR = tmp
            try:
                first = mesh_dns.apply_mesh_dns()
                self.assertTrue(first["ok"])
                self.assertTrue(os.path.exists(os.path.join(tmp, "Corefile")))
                self.assertTrue(os.path.exists(os.path.join(tmp, "mesh.hosts")))
                first_mtime = os.path.getmtime(os.path.join(tmp, "mesh.hosts"))
                second = mesh_dns.apply_mesh_dns()
                self.assertTrue(second["ok"])
                self.assertIn("unchanged", second["message"])
                self.assertEqual(first_mtime, os.path.getmtime(os.path.join(tmp, "mesh.hosts")))
            finally:
                mesh_dns.COREDNS_CONFIG_DIR = os.environ.get("COREDNS_CONFIG_DIR", "/coredns-config")


class MeshDnsApiTests(TestCase):
    """HTTP surface: PATCH /system/config/ domain + mesh dns-zone/sync-dns."""

    def setUp(self):
        from django.contrib.auth import get_user_model
        from rest_framework.test import APIClient

        self.client = APIClient()
        self.admin = get_user_model().objects.create_superuser(
            "meshdns-admin", "m@t.com", "pass"
        )
        self.client.force_authenticate(user=self.admin)

    def test_patch_domain_valid_persists_and_serves(self):
        from apps.deployments.models.core import PlatformConfig

        response = self.client.patch(
            "/api/v1/system/config/", {"MESH_DNS_DOMAIN": "Custom.Mesh"}, format="json"
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data["MESH_DNS_DOMAIN"], "custom.mesh")
        PlatformConfig.clear_cache()
        self.assertEqual(PlatformConfig.load().mesh_dns_domain, "custom.mesh")

        # Effective domain follows the DB value (no env override in tests).
        from apps.deployments.services.mesh_dns import mesh_dns_domain
        self.assertEqual(mesh_dns_domain(), "custom.mesh")

    def test_patch_domain_invalid_rejected(self):
        response = self.client.patch(
            "/api/v1/system/config/", {"MESH_DNS_DOMAIN": "not a domain!!"}, format="json"
        )
        self.assertEqual(response.status_code, 400)
        self.assertIn("error", response.data)

    def test_patch_domain_blank_keeps_existing(self):
        from apps.deployments.models.core import PlatformConfig

        config = PlatformConfig.load()
        config.mesh_dns_domain = "keep.mesh"
        config.save(update_fields=["mesh_dns_domain"])
        PlatformConfig.clear_cache()

        response = self.client.patch(
            "/api/v1/system/config/", {"MESH_DNS_DOMAIN": "   "}, format="json"
        )
        self.assertEqual(response.status_code, 200)
        PlatformConfig.clear_cache()
        self.assertEqual(PlatformConfig.load().mesh_dns_domain, "keep.mesh")

    def _make_mesh(self):
        from apps.deployments.models.mesh import MeshNetwork, WireGuardPeer

        mesh = MeshNetwork.objects.create(
            name="default", subnet="10.100.0.0/24", is_active=True,
        )
        MeshNetwork.objects.exclude(id=mesh.id).delete()
        WireGuardPeer.objects.create(
            mesh=mesh, wg_address="10.100.0.1", private_key="", public_key="x" * 44,
            is_active=True, is_local=True, allowed_ips="10.100.0.1/32",
        )
        return mesh

    def test_dns_zone_endpoint(self):
        mesh = self._make_mesh()
        response = self.client.get(f"/api/v1/mesh/{mesh.id}/dns-zone/")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.data["domain"], "mesh.internal")
        names = {record["name"] for record in response.data["records"]}
        self.assertIn("master.mesh.internal", names)
        self.assertIn("registry.mesh.internal", names)
        self.assertEqual(response.data["count"], len(response.data["records"]))

    def test_sync_dns_endpoint_queues(self):
        from unittest.mock import patch

        mesh = self._make_mesh()
        with patch(
            "apps.deployments.tasks.infra.tasks_mesh_dns.sync_mesh_dns_task.delay"
        ) as mock_delay:
            response = self.client.post(f"/api/v1/mesh/{mesh.id}/sync-dns/")
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.data["queued"])
        mock_delay.assert_called_once_with()
        self.assertGreater(response.data["count"], 0)
