"""Tests for the startup Caddy sync outage guard.

On 2026-09-06 a backend restart ran the startup Caddy sync against a
ghost/empty-domain PlatformConfig. The generator emitted a stub
Caddyfile without the control-plane site block, apply_caddyfile's own
guard ALSO skipped (same empty domain), the stub went live, Caddy
dropped its 443 listener, and every proxied request 521'd until manual
regeneration.
"""
from types import SimpleNamespace

from django.test import TestCase

from apps.deployments.services.startup import startup_sync_skip_reason

STUB = """# Grid Caddyfile - Auto-generated by Settings UI
{
    on_demand_tls {
        ask http://backend:8000/api/v1/services/check-domain/
    }
}

:80 {
    handle /api/* {
        reverse_proxy backend:8000
    }
    handle {
        reverse_proxy frontend:3000
    }
    encode gzip
}
"""

LIVE = STUB + """
grid.smsly.cloud {
    encode gzip
    handle /api/* {
        reverse_proxy backend:8000
    }
}

api.trulay.co {
    encode gzip
    handle / {
        reverse_proxy frontend:3000
    }
}
"""


class StartupSyncGuardTests(TestCase):
    def test_healthy_config_proceeds(self):
        cfg = SimpleNamespace(_is_ghost=False, domain="grid.smsly.cloud")
        self.assertIsNone(startup_sync_skip_reason(cfg))

    def test_ghost_config_skips(self):
        cfg = SimpleNamespace(_is_ghost=True, domain="grid.smsly.cloud")
        reason = startup_sync_skip_reason(cfg)
        self.assertIsNotNone(reason)
        self.assertIn("ghost", reason)

    def test_empty_domain_skips(self):
        for domain in ("", "   ", None):
            cfg = SimpleNamespace(_is_ghost=False, domain=domain)
            reason = startup_sync_skip_reason(cfg)
            self.assertIsNotNone(reason, f"domain={domain!r} must skip")

    def test_none_config_skips(self):
        self.assertIsNotNone(startup_sync_skip_reason(None))

    def test_missing_attrs_skips_safe(self):
        # A config object without the expected attributes must not
        # crash the decision — fail closed (skip).
        cfg = SimpleNamespace()
        reason = startup_sync_skip_reason(cfg)
        self.assertIsNotNone(reason)


class NoRegressionGuardTests(TestCase):
    """apply_caddyfile must refuse content that drops live site blocks,
    even when the platform domain is unreadable (the control-plane
    check's blind spot that caused the outage)."""

    def test_stub_against_live_is_refused_without_domain(self):
        from apps.deployments.services.caddy_manager.validation import (
            validate_no_site_block_regression,
        )
        errors = validate_no_site_block_regression(STUB, LIVE)
        self.assertTrue(errors, "total wipe must be refused even with unknown domain")

    def test_stub_against_live_is_refused_with_domain(self):
        from apps.deployments.services.caddy_manager.validation import (
            validate_no_site_block_regression,
        )
        errors = validate_no_site_block_regression(STUB, LIVE, platform_domain="grid.smsly.cloud")
        self.assertTrue(errors)

    def test_identical_content_passes(self):
        from apps.deployments.services.caddy_manager.validation import (
            validate_no_site_block_regression,
        )
        self.assertEqual(
            validate_no_site_block_regression(LIVE, LIVE, platform_domain="grid.smsly.cloud"),
            [],
        )

    def test_partial_tenant_removal_passes(self):
        # A tenant legitimately removing ONE custom domain regenerates
        # content missing just that block — must NOT be refused.
        from apps.deployments.services.caddy_manager.validation import (
            validate_no_site_block_regression,
        )
        partial = LIVE.replace("api.trulay.co {", "removed.example.com {")
        errors = validate_no_site_block_regression(partial, LIVE, platform_domain="grid.smsly.cloud")
        self.assertEqual(errors, [], errors)

    def test_platform_block_drop_refused(self):
        # Partial content that keeps a tenant block but drops the
        # platform block is still an outage — must be refused.
        from apps.deployments.services.caddy_manager.validation import (
            validate_no_site_block_regression,
        )
        no_platform = LIVE.replace("grid.smsly.cloud {", "removed.example.com {")
        errors = validate_no_site_block_regression(
            no_platform, LIVE, platform_domain="grid.smsly.cloud"
        )
        self.assertTrue(errors)

    def test_no_live_file_passes(self):
        # Fresh installs have nothing to regress against.
        from apps.deployments.services.caddy_manager.validation import (
            validate_no_site_block_regression,
        )
        self.assertEqual(validate_no_site_block_regression(STUB, ""), [])
        self.assertEqual(validate_no_site_block_regression(STUB, "   "), [])

    def test_label_extraction_ignores_global_and_bare_port(self):
        from apps.deployments.services.caddy_manager.validation import (
            extract_site_labels,
        )
        labels = extract_site_labels(STUB)
        self.assertEqual(labels, set())
        labels = extract_site_labels(LIVE)
        self.assertEqual(labels, {"grid.smsly.cloud", "api.trulay.co"})
