# Generated by Django 5.0.14 on 2026-02-18 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_rename_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("max_services", models.IntegerField(default=3)),
                (
                    "max_cpu_cores",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("max_memory_mb", models.IntegerField(default=512)),
                ("max_storage_gb", models.IntegerField(default=5)),
                ("max_bandwidth_gb", models.IntegerField(default=50)),
                ("max_addons", models.IntegerField(default=2)),
                ("max_custom_domains", models.IntegerField(default=1)),
                ("max_team_members", models.IntegerField(default=1)),
                ("has_auto_scaling", models.BooleanField(default=False)),
                ("has_priority_support", models.BooleanField(default=False)),
                ("has_backup", models.BooleanField(default=False)),
                ("has_server_transfer", models.BooleanField(default=False)),
                ("has_advanced_metrics", models.BooleanField(default=False)),
                ("has_ai_diagnosis", models.BooleanField(default=True)),
                (
                    "price_monthly_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "price_yearly_usd",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "stripe_price_id_monthly",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "stripe_price_id_yearly",
                    models.CharField(blank=True, max_length=100),
                ),
                ("flutterwave_plan_id", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ResourcePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("CPU", "CPU Core"),
                            ("RAM", "RAM (per GB)"),
                            ("STORAGE", "Storage (per GB)"),
                            ("BANDWIDTH", "Bandwidth (per GB)"),
                            ("ADDON_POSTGRES", "PostgreSQL"),
                            ("ADDON_REDIS", "Redis"),
                            ("ADDON_MONGODB", "MongoDB"),
                            ("ADDON_QDRANT", "Qdrant"),
                            ("AI_QUERY", "AI Query"),
                            ("BUILD_MINUTE", "Build Minute"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "price_per_unit_monthly",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("unit_label", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                            ("TRIAL", "Trial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.pricingplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_items", models.JSONField(default=list)),
                ("pdf_url", models.URLField(blank=True)),
                ("paid_at", models.DateTimeField(null=True)),
                ("due_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.usersubscription",
                    ),
                ),
            ],
        ),
    ]
