# Generated by Django 5.0.14 on 2026-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_pricingplan_resourceprice_usersubscription_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "subscription_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "overage_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("new_subscriptions", models.IntegerField(default=0)),
                ("cancellations", models.IntegerField(default=0)),
                ("active_subscribers", models.IntegerField(default=0)),
                ("trial_users", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="InfrastructureCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("VPS", "VPS Hosting"),
                            ("BANDWIDTH", "Bandwidth"),
                            ("STORAGE", "Storage"),
                            ("AI_API", "AI API Costs"),
                            ("DNS", "DNS/SSL"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
