# Generated by Django 5.0.14 on 2026-07-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_add_invoice_subscription_performance_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="infrastructurecost",
            new_name="billing_infracost_dt_type_idx",
            old_name="billing_infracost_date_type_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="billing_inv_user_status_idx",
            old_name="billing_invoice_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="billing_inv_status_paid_idx",
            old_name="billing_invoice_status_paid_idx",
        ),
        migrations.RenameIndex(
            model_name="usersubscription",
            new_name="billing_sub_status_pend_idx",
            old_name="billing_sub_status_period_end_idx",
        ),
    ]
