#!/bin/sh
# ============================================================
# Generate Infisical env file for Docker env_file directive
# Called by update.sh / fresh.sh — NOT the container entrypoint
# ============================================================
# Usage: ./infisical-gen-env.sh [output_path]
#   output_path defaults to /data/infisical.env (inside container)
#   On the host, call with the volume path instead.
# ============================================================

set -e

ENV_FILE="${1:-/data/infisical.env}"
REQUIRED_KEYS="ENCRYPTION_KEY AUTH_SECRET"

# Check if file exists and has all required keys
_needs_generate=false
if [ ! -f "$ENV_FILE" ]; then
    _needs_generate=true
else
    for _key in $REQUIRED_KEYS; do
        if ! grep -q "^${_key}=.\\+" "$ENV_FILE" 2>/dev/null; then
            echo "[infisical-gen] Missing key $_key — regenerating"
            _needs_generate=true
            break
        fi
    done
fi

if [ "$_needs_generate" = "true" ]; then
    echo "[infisical-gen] Generating Infisical env file at $ENV_FILE"

    # Generate ENCRYPTION_KEY (16-byte hex = 32 chars)
    _enc_key=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 32)

    # Generate AUTH_SECRET (32-byte base64)
    _auth_secret=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64 -w0 2>/dev/null | head -c 44)

    cat > "$ENV_FILE" <<EOF
# Auto-generated by smsly-hosting — do not edit manually
# Regenerated if missing or incomplete
ENCRYPTION_KEY=${_enc_key}
AUTH_SECRET=${_auth_secret}
EOF

    chmod 600 "$ENV_FILE"
    echo "[infisical-gen] Secrets written to $ENV_FILE"
else
    echo "[infisical-gen] Reusing existing env file at $ENV_FILE"
fi
