# Generated by Django 4.2.28 on 2026-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoscaler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoscalerconfig',
            options={'verbose_name': 'Autoscaler Config', 'verbose_name_plural': 'Autoscaler Config'},
        ),
        migrations.AlterField(
            model_name='autoscalerconfig',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
