#!/usr/bin/env bash
#
# install.sh - Local (non-Kubernetes) installer for the SMSLY Rust twin.
#
# What it does:
#   1. Checks for required host dependencies (cargo, psql, redis-cli).
#   2. Reads or generates a .env file with DATABASE_URL, REDIS_URL, JWT_SECRET.
#   3. Builds the api, worker, and cli binaries in release mode.
#   4. Runs database migrations with the cli binary.
#   5. Starts the api and worker in the background and prints next steps.
#
# This is a small, well-documented replacement for the 7,232-line Django
# installer; it targets a single host, no Docker, no orchestration.
#
# Usage:
#   ./install.sh           # install + run
#   ./install.sh build     # only build
#   ./install.sh migrate   # only run migrations
#   ./install.sh start     # only start api+worker (assumes prior build/migrate)
#   ./install.sh stop      # stop background api+worker
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

LOG_DIR="$SCRIPT_DIR/.run"
PID_FILE_API="$LOG_DIR/api.pid"
PID_FILE_WORKER="$LOG_DIR/worker.pid"
LOG_FILE_API="$LOG_DIR/api.log"
LOG_FILE_WORKER="$LOG_DIR/worker.log"
ENV_FILE="$SCRIPT_DIR/.env"

GREEN=$'\033[0;32m'
YELLOW=$'\033[0;33m'
RED=$'\033[0;31m'
RESET=$'\033[0m'

log()  { printf '%s[install]%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%s[install]%s %s\n' "$YELLOW" "$RESET" "$*" >&2; }
die()  { printf '%s[install]%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

require_cmd() {
  local cmd="$1"
  local hint="${2:-}"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    die "missing required command: $cmd${hint:+ ($hint)}"
  fi
}

ensure_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    log "creating $ENV_FILE with random secrets"
    local jwt
    jwt=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | xxd -p -c 64)
    cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DATABASE_URL=postgres://smsly_admin:smsly_password@127.0.0.1:5432/smsly_rust_twin
REDIS_URL=redis://127.0.0.1:6379/0
JWT_SECRET=$jwt
RUST_LOG=info,api=debug,core=debug
HOST=0.0.0.0
PORT=8080
EOF
    warn "edit $ENV_FILE to match your local Postgres/Redis before continuing"
  fi
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
}

check_runtime() {
  if command -v psql >/dev/null 2>&1; then
    log "checking Postgres at $DATABASE_URL"
    if ! psql "$DATABASE_URL" -c "SELECT 1" >/dev/null 2>&1; then
      warn "Postgres not reachable at $DATABASE_URL (continuing; 'migrate' will fail until it is up)"
    else
      log "Postgres OK"
    fi
  fi
  if command -v redis-cli >/dev/null 2>&1; then
    local redis_host redis_port
    redis_host=$(printf '%s' "$REDIS_URL" | sed -E 's#redis://([^:/]+).*#\1#')
    redis_port=$(printf '%s' "$REDIS_URL" | sed -E 's#redis://[^:]+:([0-9]+).*#\1#')
    log "checking Redis at $redis_host:$redis_port"
    if ! redis-cli -h "$redis_host" -p "$redis_port" ping >/dev/null 2>&1; then
      warn "Redis not reachable at $redis_host:$redis_port"
    else
      log "Redis OK"
    fi
  fi
}

do_build() {
  require_cmd cargo "https://rustup.rs/"
  log "cargo build --release (api, worker, cli)"
  cargo build --release --bin api --bin worker --bin cli
  log "binaries ready: target/release/{api,worker,cli}"
}

do_migrate() {
  require_cmd cargo
  if [[ ! -x "$SCRIPT_DIR/target/release/cli" ]]; then
    die "cli binary not found; run '$0 build' first"
  fi
  log "running migrations"
  "$SCRIPT_DIR/target/release/cli" migrate
}

start_bg() {
  local name="$1" bin="$2" pidfile="$3" logfile="$4"
  if [[ -f "$pidfile" ]] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
    warn "$name already running (pid $(cat "$pidfile"))"
    return 0
  fi
  log "starting $name in background (log: $logfile)"
  nohup "$bin" >"$logfile" 2>&1 &
  echo $! > "$pidfile"
  log "$name started (pid $(cat "$pidfile"))"
}

stop_bg() {
  local name="$1" pidfile="$2"
  if [[ -f "$pidfile" ]] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
    log "stopping $name (pid $(cat "$pidfile"))"
    kill "$(cat "$pidfile")" || true
    rm -f "$pidfile"
  else
    warn "$name not running"
  fi
}

do_start() {
  mkdir -p "$LOG_DIR"
  start_bg api    "$SCRIPT_DIR/target/release/api"    "$PID_FILE_API"    "$LOG_FILE_API"
  start_bg worker "$SCRIPT_DIR/target/release/worker" "$PID_FILE_WORKER" "$LOG_FILE_WORKER"
  log "tail logs:  tail -f $LOG_FILE_API  (or $LOG_FILE_WORKER)"
}

do_stop() {
  stop_bg api    "$PID_FILE_API"
  stop_bg worker "$PID_FILE_WORKER"
}

next_steps() {
  cat <<EOF

${GREEN}Done.${RESET}

  API logs:     tail -f $LOG_FILE_API
  Worker logs:  tail -f $LOG_FILE_WORKER
  Stop:         $0 stop
  Re-migrate:   $0 migrate

The api listens on http://0.0.0.0:${PORT:-8080}.

For Kubernetes deployment see:
  charts/smsly-rust-twin/README.md
EOF
}

usage() {
  sed -n '2,15p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

main() {
  local cmd="${1:-all}"
  mkdir -p "$LOG_DIR"
  require_cmd openssl "needed for secret generation" || true
  ensure_env

  case "$cmd" in
    build)   do_build ;;
    migrate) do_migrate ;;
    start)   do_start ;;
    stop)    do_stop ;;
    all)
      do_build
      check_runtime
      do_migrate
      do_start
      next_steps
      ;;
    -h|--help|help) usage; exit 0 ;;
    *) die "unknown command: $cmd (use build|migrate|start|stop|all)" ;;
  esac
}

main "$@"
