import logging
import os

logger = logging.getLogger(__name__)

EDGE_SHARED_FILENAME = "edge-shared.yml"


def _dynamic_dir() -> str:
    try:
        from apps.deployments.services.traefik_manager.canary_file import TRAEFIK_DYNAMIC_DIR
        return TRAEFIK_DYNAMIC_DIR
    except Exception:
        return os.environ.get("TRAEFIK_DYNAMIC_DIR", "/traefik-dynamic")


EDGE_SHARED_YML = """# =============================================================================
# SMSLY edge shared middlewares — generated by backend (edge_shared_file.py).
# DO NOT hand-edit: rewritten on deploy/health/sync. Single-writer only.
# Provides: secure-headers-strict, edge-forward-auth, sablier defaults.
# =============================================================================
http:
  middlewares:
    secure-headers-strict:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        customResponseHeaders:
          X-Frame-Options: "DENY"
          Content-Security-Policy: "frame-ancestors 'none'"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Permissions-Policy: "camera=(), microphone=(), geolocation=()"
    edge-forward-auth:
      forwardAuth:
        # Traefik runs containerized; the sidecar is a host systemd unit.
        # host.docker.internal resolves via extra_hosts: host-gateway on
        # the traefik service. 127.0.0.1 here would be Traefik itself.
        address: "http://host.docker.internal:8971/auth-verify"
        authResponseHeaders:
          - "X-User-Id"
          - "X-Edge-Scope"
    sablier-dynamic-default:
      plugin:
        sablier:
          sablierUrl: "http://sablier:10000"
          sessionDuration: "10m"
          dynamic:
            displayName: "Starting service"
            showDetails: true
            theme: "hacker-terminal"
            refreshFrequency: "5s"
"""


def ensure_edge_shared_file() -> str | None:
    path = os.path.join(_dynamic_dir(), EDGE_SHARED_FILENAME)
    try:
        if os.path.exists(path):
            with open(path) as fh:
                if fh.read() == EDGE_SHARED_YML:
                    return path
        with open(path, "w") as fh:
            fh.write(EDGE_SHARED_YML)
        return path
    except Exception as exc:
        logger.warning("Failed to write edge shared Traefik file: %s", exc)
        return None
