apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smsly-rust-twin.fullname" . }}-config
  labels:
    {{- include "smsly-rust-twin.labels" . | nindent 4 }}
data:
  RUST_LOG: "info,api=debug,core=debug"
  HOST: "0.0.0.0"
  PORT: "{{ .Values.service.port }}"
  DATABASE_HOST: {{ .Values.postgres.host | quote }}
  DATABASE_PORT: "{{ .Values.postgres.port }}"
  DATABASE_NAME: {{ .Values.postgres.database | quote }}
  DATABASE_USER: {{ .Values.postgres.user | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: "{{ .Values.redis.port }}"
