# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtls', '0002_ecosystem_trust_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtlsconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mtlsconfig',
            name='trust_domain',
            field=models.CharField(
                default='ecosystem.local',
                help_text='SPIFFE trust domain for this service.',
                max_length=255,
            ),
        ),
    ]
