# Generated by Django 5.0.14 on 2026-08-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtls', '0005_mtlsconfig_sidecar_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtlsconfig',
            name='trust_domain',
            field=models.CharField(default='platform.local', help_text='SPIFFE trust domain for this service.', max_length=255),
        ),
    ]
