# Generated by Django 5.0.14 on 2026-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtls', '0007_enable_ecosystem_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtlsconfig',
            name='sidecar_enabled',
            field=models.BooleanField(default=True, help_text='Enable Envoy sidecar for transparent mTLS. When enabled, an Envoy proxy is deployed alongside the service to handle mTLS termination/origination transparently.'),
        ),
    ]
