global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default'
  routes:
    - receiver: 'critical'
      matchers:
        - severity = critical
      repeat_interval: 1h
    - receiver: 'warning'
      matchers:
        - severity = warning

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/alerts'
        send_resolved: true
      - url: 'http://127.0.0.1:5001/alerts/fallback'
        send_resolved: true

  - name: 'critical'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/alerts'
        send_resolved: true
      - url: 'http://127.0.0.1:5001/alerts/fallback'
        send_resolved: true

  - name: 'warning'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/alerts'
        send_resolved: true
      - url: 'http://127.0.0.1:5001/alerts/fallback'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
