# Generated by Django 5.0.14 on 2026-06-30 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDeniedAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('permission_code', models.CharField(default='unknown', help_text='Permission code that was denied', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resource_id', models.UUIDField(blank=True, help_text='UUID of the resource being accessed, if available', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_denials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Denial',
                'verbose_name_plural': 'Permission Denials',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='permissions_user_id_e302e9_idx'), models.Index(fields=['permission_code', '-timestamp'], name='permissions_permiss_5bd717_idx')],
            },
        ),
    ]
