# Generated by Django 5.0.14 on 2026-02-05 02:00

import uuid

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True)),
                ('repository_url', models.URLField()),
                ('default_branch', models.CharField(default='main', max_length=50)),
                ('default_port', models.IntegerField(default=8000)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('action', models.CharField(default='unknown', max_length=255)),
                ('target', models.CharField(default='none', max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', editable=False, max_length=64)),
                ('hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', editable=False, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['hash'], name='deployments_hash_fe5aec_idx'), models.Index(fields=['actor'], name='deployments_actor_0cbddc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('repository_url', models.URLField(blank=True, help_text='Git repository URL', null=True)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('deploy_type', models.CharField(choices=[('GIT', 'Git Repository'), ('DOCKER', 'Docker Image'), ('UPLOAD', 'File Upload'), ('TEMPLATE', 'Predefined Template')], default='GIT', max_length=20)),
                ('docker_image', models.CharField(blank=True, max_length=255, null=True)),
                ('build_command', models.CharField(blank=True, max_length=255, null=True)),
                ('start_command', models.CharField(blank=True, max_length=255, null=True)),
                ('root_directory', models.CharField(default='/', max_length=255)),
                ('internal_port', models.IntegerField(default=8000)),
                ('public_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('domain_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('cpu_cores', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('memory_mb', models.IntegerField(default=512)),
                ('min_replicas', models.IntegerField(default=1)),
                ('max_replicas', models.IntegerField(default=1)),
                ('autoscale_cpu_target', models.IntegerField(default=80, help_text='Target CPU utilization percentage')),
                ('use_blue_green', models.BooleanField(default=False, help_text='Use Blue/Green deployment strategy')),
                ('is_preview', models.BooleanField(default=False)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('coolify_uuid', models.CharField(blank=True, help_text='UUID of the application in Coolify', max_length=64, null=True, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('parent_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='deployments.service')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='cloud.cloudprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(max_length=40)),
                ('commit_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('BUILDING', 'Building'), ('DEPLOYING', 'Deploying'), ('HEALTH_CHECK', 'Health Check'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('build_logs', models.TextField(blank=True)),
                ('runtime_logs_url', models.URLField(blank=True, null=True)),
                ('ai_diagnosis', models.TextField(blank=True, help_text='AI suggested fix for failure')),
                ('vulnerability_report', models.JSONField(blank=True, default=dict, help_text='Trivy scan results')),
                ('container_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='deployments.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schedule', models.CharField(help_text="Cron schedule e.g. '*/5 * * * *'", max_length=100)),
                ('command', models.CharField(help_text='Command to execute inside the container', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to='deployments.service')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hipaa_compliant', models.BooleanField(default=False)),
                ('gdpr_compliant', models.BooleanField(default=False)),
                ('soc2_compliant', models.BooleanField(default=False)),
                ('data_residency', models.CharField(default='us-east-1', max_length=50)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='deployments.service')),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('addon_type', models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('REDIS', 'Redis'), ('MYSQL', 'MySQL'), ('MONGODB', 'MongoDB')], max_length=20)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='PROVISIONING', max_length=20)),
                ('connection_url', models.CharField(blank=True, max_length=512)),
                ('coolify_uuid', models.CharField(blank=True, help_text='UUID of the database in Coolify', max_length=64, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='deployments.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu_usage', models.DecimalField(decimal_places=4, help_text='CPU cores used', max_digits=10)),
                ('memory_usage', models.IntegerField(help_text='Memory used in MB')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='deployments.service')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mount_path', models.CharField(help_text='Path inside container e.g. /data', max_length=255)),
                ('size_gb', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='deployments.service')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('value', encrypted_model_fields.fields.EncryptedCharField()),
                ('is_secret', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_vars', to='deployments.service')),
            ],
            options={
                'unique_together': {('service', 'key')},
            },
        ),
    ]
