# Generated by Django 6.0.1 on 2026-01-28 07:35

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("repository_url", models.URLField(help_text="Git repository URL")),
                ("branch", models.CharField(default="main", max_length=255)),
                (
                    "build_command",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start_command",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("root_directory", models.CharField(default="/", max_length=255)),
                ("internal_port", models.IntegerField(default=8000)),
                (
                    "public_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "cpu_cores",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
                ),
                ("memory_mb", models.IntegerField(default=512)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("commit_hash", models.CharField(max_length=40)),
                ("commit_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("BUILDING", "Building"),
                            ("DEPLOYING", "Deploying"),
                            ("HEALTH_CHECK", "Health Check"),
                            ("ACTIVE", "Active"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("build_logs", models.TextField(blank=True)),
                ("runtime_logs_url", models.URLField(blank=True, null=True)),
                (
                    "container_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hipaa_compliant", models.BooleanField(default=False)),
                ("gdpr_compliant", models.BooleanField(default=False)),
                ("soc2_compliant", models.BooleanField(default=False)),
                (
                    "data_residency",
                    models.CharField(default="us-east-1", max_length=50),
                ),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance",
                        to="deployments.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvironmentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255)),
                ("value", encrypted_model_fields.fields.EncryptedCharField()),
                ("is_secret", models.BooleanField(default=False)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="env_vars",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "unique_together": {("service", "key")},
            },
        ),
    ]
