"""0002 Addon module."""
# Generated by Django 6.0.1 on 2026-01-28 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addon",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "addon_type",
                    models.CharField(
                        choices=[
                            ("POSTGRES", "PostgreSQL"), ("REDIS", "Redis")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROVISIONING", "Provisioning"),
                            ("ACTIVE", "Active"),
                            ("FAILED", "Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PROVISIONING",
                        max_length=20,
                    ),
                ),
                ("connection_url", models.CharField(blank=True, max_length=512)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
