# Generated by Django 6.0.1 on 2026-01-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0002_addon"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cpu_usage",
                    models.DecimalField(
                        decimal_places=4, help_text="CPU cores used", max_digits=10
                    ),
                ),
                ("memory_usage", models.IntegerField(help_text="Memory used in MB")),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
