# Generated by Django 5.0.14 on 2026-02-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_tunnel_tunnelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='is_rollback',
            field=models.BooleanField(default=False, help_text='Whether this deployment is a rollback'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='rollback_from',
            field=models.ForeignKey(blank=True, help_text='The deployment this was rolled back from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_deployments', to='deployments.deployment'),
        ),
        migrations.AddField(
            model_name='service',
            name='canary_percentage',
            field=models.IntegerField(default=10, help_text='Percentage of traffic routed to canary (1-100)'),
        ),
        migrations.AddField(
            model_name='service',
            name='deploy_strategy',
            field=models.CharField(choices=[('ROLLING', 'Rolling Update'), ('BLUE_GREEN', 'Blue/Green'), ('CANARY', 'Canary')], default='ROLLING', help_text='Deployment strategy for this service', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='use_blue_green',
            field=models.BooleanField(default=False, help_text='Deprecated: use deploy_strategy instead'),
        ),
    ]
