"""0004 Template Service Domain Verified And More module."""
# Generated by Django 6.0.1 on 2026-01-28 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0003_servicemetric"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("icon_url", models.URLField(blank=True)),
                ("repository_url", models.URLField()),
                ("default_branch", models.CharField(
                    default="main", max_length=50)),
                ("default_port", models.IntegerField(default=8000)),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="domain_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="verification_token",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
