# Generated by Django 5.0.14 on 2026-02-09 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_deployment_pipeline_phase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('provider', models.CharField(default='aws', max_length=50)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='vpa_enabled',
            field=models.BooleanField(default=False, help_text='Enable Vertical Pod Autoscaling (VPA)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='autoscale_cpu_target',
            field=models.IntegerField(default=80, help_text='Target CPU utilization percentage (HPA)'),
        ),
        migrations.AddField(
            model_name='service',
            name='primary_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_services', to='deployments.region'),
        ),
        migrations.AddField(
            model_name='service',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='Regions to deploy this service to', related_name='services', to='deployments.region'),
        ),
    ]
