"""0005 Deployment Ai Diagnosis And More module."""
# Generated by Django 6.0.1 on 2026-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0004_template_service_domain_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="ai_diagnosis",
            field=models.TextField(
                blank=True, help_text="AI suggested fix for failure"
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="vulnerability_report",
            field=models.JSONField(
                blank=True, default=dict, help_text="Trivy scan results"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="autoscale_cpu_target",
            field=models.IntegerField(
                default=80, help_text="Target CPU utilization percentage"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="max_replicas",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="service",
            name="min_replicas",
            field=models.IntegerField(default=1),
        ),
    ]
