"""0006 Service Is Preview Service Parent Service And More module."""
# Generated by Django 6.0.1 on 2026-01-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0005_deployment_ai_diagnosis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="parent_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="previews",
                to="deployments.service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="pr_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CronJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "schedule",
                    models.CharField(
                        help_text="Cron expression (e.g., '0 * * * *')", max_length=100
                    ),
                ),
                ("command", models.CharField(max_length=512)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cron_jobs",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
