# Generated by Django 5.2.11 on 2026-02-12 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_managed_services_backups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_replicas',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_replicas',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
