# Generated by Django 6.0.1 on 2026-01-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0006_service_is_preview_service_parent_service_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mount_path",
                    models.CharField(
                        help_text="Path in container e.g. /data", max_length=255
                    ),
                ),
                ("size_gb", models.IntegerField(default=1)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volumes",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
