# Generated by Django 6.0.1 on 2026-01-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0007_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="use_blue_green",
            field=models.BooleanField(
                default=False, help_text="Use Blue/Green deployment strategy"
            ),
        ),
    ]
