# Generated by Django 5.2.8 on 2026-01-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_service_use_blue_green'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='coolify_uuid',
            field=models.CharField(blank=True, help_text='UUID of the database in Coolify', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='coolify_uuid',
            field=models.CharField(blank=True, help_text='UUID of the application in Coolify', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='addon_type',
            field=models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('REDIS', 'Redis'), ('MYSQL', 'MySQL'), ('MONGODB', 'MongoDB')], max_length=20),
        ),
    ]
