"""0010 Service Deploy Type Service Docker Image And More module."""
# Generated by Django 5.0.14 on 2026-01-30 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud", "0001_initial"),
        ("deployments", "0009_addon_coolify_uuid_service_coolify_uuid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="deploy_type",
            field=models.CharField(
                choices=[
                    ("GIT", "Git Repository"),
                    ("DOCKER", "Docker Image"),
                    ("UPLOAD", "File Upload"),
                    ("TEMPLATE", "Predefined Template"),
                ],
                default="GIT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="docker_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="cloud.cloudprovider",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="repository_url",
            field=models.URLField(
                blank=True, help_text="Git repository URL", null=True
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(
                    blank=True, max_length=512, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("SERVICE_CREATE", "Service Created"),
                            ("SERVICE_DELETE", "Service Deleted"),
                            ("SERVICE_UPDATE", "Service Updated"),
                            ("DEPLOYMENT_START", "Deployment Started"),
                            ("DEPLOYMENT_SUCCESS", "Deployment Succeeded"),
                            ("DEPLOYMENT_FAIL", "Deployment Failed"),
                            ("DEPLOYMENT_ROLLBACK", "Deployment Rollback"),
                            ("ENV_VAR_CREATE", "Environment Variable Created"),
                            ("ENV_VAR_UPDATE", "Environment Variable Updated"),
                            ("ENV_VAR_DELETE", "Environment Variable Deleted"),
                            ("ADDON_PROVISION", "Addon Provisioned"),
                            ("ADDON_DEPROVISION", "Addon Deprovisioned"),
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("TOKEN_REFRESH", "Token Refreshed"),
                            ("ADMIN_IMPERSONATE", "Admin Impersonation"),
                            ("PERMISSION_CHANGE", "Permission Changed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(db_index=True, max_length=50)),
                ("resource_id", models.CharField(db_index=True, max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "permissions": [("view_audit_log", "Can view audit logs")],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "action_type"],
                        name="deployments_timesta_0bc7b4_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="deployments_user_id_8cd993_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="deployments_resourc_6c2e25_idx",
                    ),
                ],
            },
        ),
    ]
