"""0011 Alter Auditlog Options And More module."""
# Generated by Django 5.0.14 on 2026-02-02 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0010_service_deploy_type_service_docker_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="deployments_timesta_0bc7b4_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="deployments_user_id_8cd993_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="deployments_resourc_6c2e25_idx",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="action_type",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="details",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="resource_id",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="resource_type",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user_email",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="action",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.CharField(default="system", max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="hash",
            field=models.CharField(
                default="0000000000000000000000000000000000000000000000000000000000000000",
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="previous_hash",
            field=models.CharField(
                default="0000000000000000000000000000000000000000000000000000000000000000",
                editable=False,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="target",
            field=models.CharField(default="none", max_length=255),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["hash"],
                name="deployments_hash_fe5aec_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor"],
                name="deployments_actor_0cbddc_idx"),
        ),
    ]
