"""0012 Remove Volume Updated At Cronjob Is Active And More module."""
# Generated by Django 5.0.14 on 2026-02-02 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0011_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volume",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="cronjob",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="last_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cronjob",
            name="next_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volume",
            name="name",
            field=models.CharField(default="default-volume", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="command",
            field=models.CharField(
                help_text="Command to execute inside the container", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cronjob",
            name="schedule",
            field=models.CharField(
                help_text="Cron schedule e.g. '*/5 * * * *'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="mount_path",
            field=models.CharField(
                help_text="Path inside container e.g. /data", max_length=255
            ),
        ),
    ]
