# Generated by Django 5.0.14 on 2026-02-16 23:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0011_service_custom_domains"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label, e.g. 'My Laptop CLI'",
                        max_length=100,
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 8 chars of the token for lookup",
                        max_length=12,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the full token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "API Token",
                "ordering": ["-created_at"],
            },
        ),
        # State-only RenameIndex: the index may or may not exist with the old name
        # depending on whether 0009 was applied or faked. Safe to update state only.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="servicemetric",
                    new_name="deployments_service_d8ff01_idx",
                    old_name="deployments_svc_ts_idx",
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="service",
            name="buildpack",
            field=models.CharField(
                choices=[
                    ("NIXPACKS", "Nixpacks"),
                    ("DOCKER", "Dockerfile"),
                    ("STATIC", "Static Site"),
                ],
                default="NIXPACKS",
                help_text="Build strategy for source code deployments",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="platformconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="servicemetric",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
