# Generated by Django 5.0.14 on 2026-02-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0012_apitoken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="pipeline_stages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of pipeline stages (name, status, duration)",
            ),
        ),
    ]
