# Generated by Django 5.0.14 on 2026-02-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0013_deployment_pipeline_stages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="deploy_type",
            field=models.CharField(
                choices=[
                    ("GIT", "Git Repository"),
                    ("DOCKER", "Docker Image"),
                    ("UPLOAD", "File Upload"),
                    ("TEMPLATE", "Predefined Template"),
                    ("FUNCTION", "Serverless Function"),
                ],
                default="GIT",
                max_length=20,
            ),
        ),
    ]
