# Generated by Django 5.0.14 on 2026-02-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0014_alter_service_deploy_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="function_code",
            field=models.TextField(
                blank=True, help_text="Raw source code for serverless functions"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="function_runtime",
            field=models.CharField(
                default="nodejs18",
                help_text="Runtime environment (e.g. nodejs18, python3.9)",
                max_length=50,
            ),
        ),
    ]
