# Generated by Django 4.2.28 on 2026-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0017_encrypt_addon_connection_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='addon_type',
            field=models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('REDIS', 'Redis'), ('MYSQL', 'MySQL'), ('MONGODB', 'MongoDB'), ('QDRANT', 'Qdrant (Vector DB)')], max_length=20),
        ),
    ]
