# Generated by Django 5.0.14 on 2026-02-18 18:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0020_serverbackup_backupschedule_servicebackup"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREPARING", "Preparing"),
                            ("UPLOADING", "Uploading"),
                            ("RESTORING", "Restoring"),
                            ("DNS_CUTOVER", "DNS Cutover"),
                            ("VERIFYING", "Verifying"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="PREPARING",
                        max_length=20,
                    ),
                ),
                ("source_server_ip", models.GenericIPAddressField()),
                ("target_server_ip", models.GenericIPAddressField()),
                ("target_ssh_key", models.TextField(blank=True)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Single Service"),
                            ("FULL", "Full Server"),
                        ],
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=200)),
                ("logs", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_downtime_seconds", models.IntegerField(default=0)),
                ("can_rollback", models.BooleanField(default=True)),
                ("rollback_deadline", models.DateTimeField(null=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deployments.service",
                    ),
                ),
                (
                    "source_backup",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deployments.servicebackup",
                    ),
                ),
            ],
        ),
    ]
