# Generated by Django 5.0.14 on 2026-02-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0021_servertransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="servertransfer",
            name="source_server_backup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deployments.serverbackup",
            ),
        ),
        migrations.AlterField(
            model_name="servertransfer",
            name="source_backup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deployments.servicebackup",
            ),
        ),
    ]
