# Generated by Django 4.2.28 on 2026-02-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0022_servertransfer_source_server_backup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addon",
            name="addon_type",
            field=models.CharField(
                choices=[
                    ("POSTGRES", "PostgreSQL"),
                    ("REDIS", "Redis"),
                    ("MYSQL", "MySQL"),
                    ("MONGODB", "MongoDB"),
                    ("QDRANT", "Qdrant (Vector DB)"),
                    ("ELASTICSEARCH", "Elasticsearch"),
                ],
                max_length=20,
            ),
        ),
    ]
