# Generated by Django 4.2.28 on 2026-02-21 08:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deployments', '0023_add_elasticsearch_addon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable project name, e.g. 'SMSLY Platform'", max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-generated from name', max_length=120)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of what this project contains')),
                ('icon_emoji', models.CharField(default='📦', help_text='Emoji icon shown in the UI', max_length=10)),
                ('color', models.CharField(default='#6366f1', help_text="Hex color for project accent, e.g. '#10b981'", max_length=7)),
                ('is_default', models.BooleanField(default=False, help_text='If true, new services without a project are assigned here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'ordering': ['-is_default', '-updated_at'],
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this service belongs to (null = ungrouped)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='deployments.project'),
        ),
    ]
