# Generated by Django 5.0.14 on 2026-02-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0027_service_health_check_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentvariable",
            name="source",
            field=models.CharField(
                choices=[
                    ("USER", "User Defined"),
                    ("ADDON", "Addon Auto-Injected"),
                    ("SHORTCODE", "Shortcode Resolved"),
                ],
                default="USER",
                help_text="Origin of this env var",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="If False, Traefik route is disabled; service only reachable via Docker DNS",
            ),
        ),
    ]
