# Generated by Django 5.0.14 on 2026-02-25 17:17
# This is the original 0028 that was applied on some VPS instances
# before the repo's 0028 was expanded to include env source field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0027_service_health_check_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="If False, Traefik route is disabled; service only reachable via Docker DNS",
            ),
        ),
    ]
