# Generated by Django 5.0.14 on 2026-02-25 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0028_environmentvariable_source_alter_service_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PULLING", "Pulling Images"),
                            ("BACKING_UP", "Backing Up"),
                            ("MIGRATING", "Running Migrations"),
                            ("RESTARTING", "Restarting Services"),
                            ("HEALTH_CHECK", "Health Check"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("from_version", models.CharField(blank=True, max_length=50)),
                ("to_version", models.CharField(blank=True, max_length=50)),
                ("from_commit", models.CharField(blank=True, max_length=40)),
                ("to_commit", models.CharField(blank=True, max_length=40)),
                ("progress_percent", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=200)),
                ("logs", models.TextField(blank=True)),
                (
                    "snapshot_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of container image tags before update",
                    ),
                ),
                ("can_rollback", models.BooleanField(default=True)),
                ("rollback_deadline", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.CharField(
                        default="manual",
                        help_text="'manual', 'auto', or 'api'",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
