# Generated by Django 5.1.7 on 2026-02-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0030_merge_0028_0029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="health_check_interval",
            field=models.IntegerField(
                default=60,
                help_text="Seconds between health checks",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="health_check_retries",
            field=models.IntegerField(
                default=8,
                help_text="Consecutive failures before marking unhealthy",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="health_check_timeout",
            field=models.IntegerField(
                default=15,
                help_text="Seconds to wait for health check response",
            ),
        ),
    ]
