# Generated by Django 4.2.28 on 2026-02-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0031_relax_health_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='green_container_id',
            field=models.CharField(blank=True, help_text='Temp container ID during STAGED bake period', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='staged_at',
            field=models.DateTimeField(blank=True, help_text='When container entered STAGED status (bake clock start)', null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('REVIEW', 'Review'), ('BUILDING', 'Building'), ('DEPLOYING', 'Deploying'), ('HEALTH_CHECK', 'Health Check'), ('STAGED', 'Staged'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20),
        ),
    ]
