# Generated by Django 4.2.28 on 2026-03-11 20:17

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0038_servertransfer_target_ssh_password'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='heartbeatlog',
            new_name='deployments_cluster_539d8b_idx',
            old_name='deployments_heartbe_cluster_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wireguardpeer',
            unique_together={('mesh', 'wg_address')},
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='allowed_ips',
            field=models.CharField(default='', help_text='Comma-separated CIDR ranges this peer can route', max_length=500),
        ),
        migrations.AddField(
            model_name='wireguardpeer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meshnetwork',
            name='interface_name',
            field=models.CharField(default='wg0', help_text='WireGuard interface name', max_length=15),
        ),
        migrations.AlterField(
            model_name='meshnetwork',
            name='listen_port',
            field=models.IntegerField(default=51820, help_text='WireGuard listen port on each server'),
        ),
        migrations.AlterField(
            model_name='meshnetwork',
            name='name',
            field=models.CharField(default='default', help_text="Mesh network name (e.g. 'production', 'staging')", max_length=100),
        ),
        migrations.AlterField(
            model_name='meshnetwork',
            name='subnet',
            field=models.CharField(default='10.100.0.0/24', help_text='WireGuard subnet CIDR (e.g. 10.100.0.0/24)', max_length=18),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='endpoint',
            field=models.CharField(blank=True, default='', help_text='Public IP:port for this peer (e.g. 163.245.216.248:51820)', max_length=255),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='is_local',
            field=models.BooleanField(default=False, help_text='True if this peer represents the local (this) server'),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='last_handshake',
            field=models.DateTimeField(blank=True, help_text='Last WireGuard handshake time', null=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='latency_ms',
            field=models.FloatField(blank=True, help_text='Last measured ping latency in ms', null=True),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='private_key',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='WireGuard private key (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='public_key',
            field=models.CharField(help_text='WireGuard public key (safe to share)', max_length=44),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='server',
            field=models.ForeignKey(blank=True, help_text='Linked ManagedServer (null for the local/primary server)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wg_peers', to='deployments.managedserver'),
        ),
        migrations.AlterField(
            model_name='wireguardpeer',
            name='wg_address',
            field=models.GenericIPAddressField(help_text="This peer's IP inside the WireGuard mesh (e.g. 10.100.0.1)", protocol='IPv4'),
        ),
        migrations.AlterUniqueTogether(
            name='wireguardpeer',
            unique_together={('mesh', 'wg_address'), ('mesh', 'server')},
        ),
    ]
