# Generated by Django 4.2.28 on 2026-03-11 20:36

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0039_rename_deployments_heartbe_cluster_idx_deployments_cluster_539d8b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedserver',
            name='api_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='api_url',
            field=models.URLField(blank=True, default='', help_text='Full URL to the SMSLY Hosting API'),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='gateway_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='role',
            field=models.CharField(choices=[('LEADER', 'Leader'), ('FOLLOWER', 'Follower'), ('CANDIDATE', 'Candidate')], default='FOLLOWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='ssh_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='ssh_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='ssh_user',
            field=models.CharField(default='root', max_length=100),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='wg_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon_emoji',
            field=models.CharField(default='📦', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
    ]
