# Generated by Django 5.0.14 on 2026-03-13 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "deployments",
            "0041_merge_0002_service_public_domain_hidden_0040_alter_managedserver_api_token_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this addon belongs to (null = ungrouped)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_addons",
                to="deployments.project",
            ),
        ),
        migrations.AddField(
            model_name="managedserver",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this server belongs to (null = ungrouped)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_servers",
                to="deployments.project",
            ),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this mesh network belongs to (null = ungrouped)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mesh_networks",
                to="deployments.project",
            ),
        ),
    ]
