# Generated by Django 5.0.14 on 2026-03-15 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0043_auto_project_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="health_webhook_token",
            field=models.CharField(
                blank=True,
                help_text="Token for the service to push health status to the platform",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="cpu_cores",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="service",
            name="health_check_interval",
            field=models.IntegerField(
                default=30, help_text="Seconds between health checks"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="health_check_retries",
            field=models.IntegerField(
                default=90, help_text="Consecutive failures before marking unhealthy"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="max_replicas",
            field=models.IntegerField(
                default=3, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="memory_mb",
            field=models.IntegerField(default=2048),
        ),
        migrations.AlterField(
            model_name="service",
            name="vpa_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable Vertical Pod Autoscaling (VPA)"
            ),
        ),
    ]
