# Generated by Django 5.0.14 on 2026-03-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "deployments",
            "0044_service_health_webhook_token_alter_service_cpu_cores_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="health_check_timeout",
            field=models.IntegerField(
                default=300, help_text="Seconds to wait for health check response"
            ),
        ),
    ]
