# Generated by Django 5.0.14 on 2026-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0045_alter_service_health_check_timeout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="vpa_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable Vertical Pod Autoscaling (VPA)"
            ),
        ),
    ]
