# Generated by Django 4.2.28 on 2026-03-17 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0046_alter_service_vpa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='server',
            field=models.ForeignKey(blank=True, help_text='The managed server where this service is currently hosted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_on_node', to='deployments.managedserver'),
        ),
    ]
