# Generated by Django 5.0.14 on 2026-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0047_service_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="public_domain",
            field=models.CharField(
                blank=True,
                help_text="Public domain assigned to expose this addon externally via proxy",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="cpu_cores",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
