# Generated by Django 4.2.28 on 2026-03-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0048_addon_public_domain_alter_service_cpu_cores'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='is_bucket_public',
            field=models.BooleanField(default=False, help_text='Whether the default bucket is public read-only.'),
        ),
    ]
