# Generated by Django 4.2.28 on 2026-04-26 21:35

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deployments', '0049_addon_is_bucket_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='auto_create_preview_on_branch_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='migration_auto_approval_policy',
            field=models.CharField(choices=[('NEVER', 'Never'), ('LOW_RISK_ONLY', 'Low Risk Only'), ('LOW_AND_MEDIUM', 'Low and Medium'), ('ALWAYS_REQUIRE_MANUAL', 'Always Require Manual')], default='LOW_RISK_ONLY', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='preview_environments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='production_requires_backup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='safe_deploy_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('REVIEW', 'Review'), ('BUILDING', 'Building'), ('BUILD_FAILED', 'Build Failed'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('BACKUP_RUNNING', 'Backup Running'), ('BACKUP_FAILED', 'Backup Failed'), ('MIGRATION_PLANNING', 'Migration Planning'), ('MIGRATION_RUNNING', 'Migration Running'), ('MIGRATION_FAILED', 'Migration Failed'), ('DEPLOYING', 'Deploying'), ('HEALTH_CHECK', 'Health Check'), ('TRAFFIC_SHIFTING', 'Traffic Shifting'), ('MONITORING', 'Monitoring'), ('STAGED', 'Staged'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('ROLLING_BACK', 'Rolling Back'), ('ROLLED_BACK', 'Rolled Back')], default='QUEUED', max_length=20),
        ),
        migrations.CreateModel(
            name='PreviewEnvironment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('branch_name', models.CharField(max_length=255)),
                ('commit_sha', models.CharField(max_length=64)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('image_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BUILDING', 'Building'), ('BUILD_FAILED', 'Build Failed'), ('PROVISIONING', 'Provisioning'), ('DB_CLONE_CREATING', 'DB Clone Creating'), ('DB_CLONE_FAILED', 'DB Clone Failed'), ('MIGRATION_RUNNING', 'Migration Running'), ('MIGRATION_FAILED', 'Migration Failed'), ('TESTS_RUNNING', 'Tests Running'), ('TESTS_FAILED', 'Tests Failed'), ('HEALTH_CHECK_RUNNING', 'Health Check Running'), ('HEALTH_CHECK_FAILED', 'Health Check Failed'), ('READY', 'Ready'), ('EXPIRED', 'Expired'), ('DESTROYING', 'Destroying'), ('DESTROYED', 'Destroyed')], default='PENDING', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_environments', to='deployments.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MigrationValidation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='0 to 100')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('INCOMPLETE', 'Incomplete'), ('SKIPPED', 'Skipped'), ('NOT_CONFIGURED', 'Not Configured')], default='PENDING', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('detected_operations', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('requires_manual_approval', models.BooleanField(default=False)),
                ('requires_backup', models.BooleanField(default=False)),
                ('can_auto_deploy', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('deployment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_validation', to='deployments.deployment')),
                ('preview_environment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migration_validation', to='deployments.previewenvironment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthCheckResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='deployments.deployment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='deployments.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeploymentArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('BUILD_LOG', 'Build Log'), ('MIGRATION_PLAN', 'Migration Plan'), ('MIGRATION_OUTPUT', 'Migration Output'), ('TEST_OUTPUT', 'Test Output'), ('HEALTH_CHECK_OUTPUT', 'Health Check Output'), ('RISK_REPORT', 'Risk Report'), ('DEPLOYMENT_REPORT', 'Deployment Report'), ('ROLLBACK_REPORT', 'Rollback Report')], max_length=30)),
                ('content', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='deployments.deployment')),
                ('preview_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='deployments.previewenvironment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='deployments.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeploymentApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('AUTO_APPROVED', 'Auto Approved')], default='PENDING', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_approvals', to=settings.AUTH_USER_MODEL)),
                ('deployment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='deployments.deployment')),
                ('preview_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='deployments.previewenvironment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deployments.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseClone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_environment', models.CharField(default='production', max_length=50)),
                ('source_database_name', models.CharField(max_length=255)),
                ('clone_database_name', models.CharField(max_length=255)),
                ('clone_database_url_secret_ref', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREATING', 'Creating'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('DESTROYING', 'Destroying'), ('DESTROYED', 'Destroyed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('preview_environment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database_clone', to='deployments.previewenvironment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_clones', to='deployments.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
