# Generated by Django 5.0.14 on 2026-04-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0050_service_auto_create_preview_on_branch_push_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="deletion_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DELETION_PENDING", "Deletion Pending"),
                    ("DELETION_FAILED", "Deletion Failed"),
                    ("DELETED", "Deleted"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
