# Generated by Django 5.0.14 on 2026-04-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0051_service_deletion_error_service_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addon",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROVISIONING", "Provisioning"),
                    ("ACTIVE", "Active"),
                    ("FAILED", "Failed"),
                    ("DELETED", "Deleted"),
                    ("DELETION_PENDING", "Deletion Pending"),
                    ("DELETION_FAILED", "Deletion Failed"),
                ],
                default="PROVISIONING",
                max_length=20,
            ),
        ),
    ]
