# Generated by Django 4.2.28 on 2026-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0054_servertransfer_owner_encrypt_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedserver',
            name='private_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Internal/Private IP (e.g. AWS Private IP 172.31.x.x)', null=True, protocol='IPv4'),
        ),
        migrations.AddField(
            model_name='managedserver',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Cloud provider metadata (VPC ID, Instance ID, etc.)'),
        ),
        migrations.AddField(
            model_name='servertransfer',
            name='is_incoming',
            field=models.BooleanField(default=False, help_text='True if this node is the target'),
        ),
        migrations.AddField(
            model_name='servertransfer',
            name='source_node_id',
            field=models.CharField(blank=True, help_text='ID/IP of the initiating node', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='host',
            field=models.CharField(help_text="Public IP address or domain, e.g. '198.51.100.5' or 'prod.example.com'", max_length=255),
        ),
    ]
