# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0055_managedserver_private_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedserver",
            name="allow_user_workloads",
            field=models.BooleanField(
                default=True,
                help_text="When false, user services cannot be scheduled to this server.",
            ),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="mesh_status",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("DEPLOYING", "Deploying"),
                    ("ACTIVE", "Active"),
                    ("FAILED", "Failed"),
                ],
                default="UNKNOWN",
                help_text="Last known WireGuard deployment state.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="mesh_last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="mesh_last_result",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="mesh_last_deployed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="replication_status",
            field=models.CharField(
                choices=[
                    ("DISABLED", "Disabled"),
                    ("DEPLOYING", "Deploying"),
                    ("ACTIVE", "Active"),
                    ("FAILED", "Failed"),
                ],
                default="DISABLED",
                help_text="Last known Patroni replication state.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="replication_last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="replication_last_result",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="meshnetwork",
            name="replication_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
