# Generated by Django 4.2.28 on 2026-05-02 05:48

import re

from django.db import migrations, models

POSTGRES_LOCK_TIMEOUT = '15s'
POSTGRES_STATEMENT_TIMEOUT = '120s'


def _set_postgres_timeouts(schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(f"SET lock_timeout TO '{POSTGRES_LOCK_TIMEOUT}'")
    schema_editor.execute(f"SET statement_timeout TO '{POSTGRES_STATEMENT_TIMEOUT}'")


def _column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor,
            table_name,
        )

    return {
        getattr(column, 'name', column[0])
        for column in description
    }


def ensure_service_slug_column(apps, schema_editor):
    _set_postgres_timeouts(schema_editor)
    Service = apps.get_model('deployments', 'Service')
    table_name = Service._meta.db_table
    if 'slug' in _column_names(schema_editor, table_name):
        return

    quote_name = schema_editor.quote_name
    schema_editor.execute(
        f'ALTER TABLE {quote_name(table_name)} '
        f'ADD COLUMN {quote_name("slug")} varchar(255) NULL'
    )


def _dedupe_slug(base, used_slugs):
    base = (base or 'service').strip('-')[:255] or 'service'
    slug = base
    counter = 1

    while slug in used_slugs:
        suffix = f'-{counter}'
        slug = f"{base[:255 - len(suffix)].rstrip('-')}{suffix}"
        counter += 1

    used_slugs.add(slug)
    return slug


def _service_slug_base(service):
    raw = service.slug or service.name or ''
    base = re.sub(r'[^a-z0-9]+', '-', raw.lower()).strip('-')
    if base:
        return base

    return str(service.id)[:8] or 'service'


def populate_service_slugs(apps, schema_editor):
    Service = apps.get_model('deployments', 'Service')
    used_slugs = set()
    batch_size = 500

    last_id = 0
    while True:
        # Use direct ID filtering to avoid server-side cursors in non-atomic migrations.
        # This is safer when running through proxies like pgcat.
        batch = list(Service.objects.filter(id__gt=last_id)
                     .only('id', 'name', 'slug')
                     .order_by('id')[:batch_size])

        if not batch:
            break

        to_update = []
        for service in batch:
            slug = _dedupe_slug(_service_slug_base(service), used_slugs)
            if service.slug != slug:
                service.slug = slug
                to_update.append(service)
            last_id = service.id

        if to_update:
            Service.objects.bulk_update(to_update, ['slug'])


def cleanup_service_slug_artifacts(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    _set_postgres_timeouts(schema_editor)
    Service = apps.get_model('deployments', 'Service')
    table_name = schema_editor.quote_name(Service._meta.db_table)
    constraint_name = schema_editor.quote_name('deployments_service_slug_key')
    like_index_name = schema_editor.quote_name('deployments_service_slug_6f89c844_like')

    schema_editor.execute(
        f'ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS {constraint_name}'
    )
    schema_editor.execute(f'DROP INDEX CONCURRENTLY IF EXISTS {constraint_name}')
    schema_editor.execute(f'DROP INDEX CONCURRENTLY IF EXISTS {like_index_name}')


def _constraint_exists(schema_editor, constraint_name):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1
            FROM pg_constraint
            WHERE conname = %s
            """,
            [constraint_name],
        )
        return cursor.fetchone() is not None


def enforce_service_slug_constraints(apps, schema_editor):
    Service = apps.get_model('deployments', 'Service')

    if schema_editor.connection.vendor != 'postgresql':
        old_field = models.SlugField(blank=True, max_length=255, null=True)
        old_field.set_attributes_from_name('slug')
        new_field = models.SlugField(blank=True, max_length=255, unique=True)
        new_field.set_attributes_from_name('slug')
        schema_editor.alter_field(Service, old_field, new_field)
        return

    _set_postgres_timeouts(schema_editor)
    table_name = schema_editor.quote_name(Service._meta.db_table)
    column_name = schema_editor.quote_name('slug')
    constraint_name = 'deployments_service_slug_key'
    quoted_constraint = schema_editor.quote_name(constraint_name)
    like_index_name = schema_editor.quote_name('deployments_service_slug_like')

    schema_editor.execute(
        f'ALTER TABLE {table_name} ALTER COLUMN {column_name} SET NOT NULL'
    )

    if not _constraint_exists(schema_editor, constraint_name):
        schema_editor.execute(
            f'CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS {quoted_constraint} '
            f'ON {table_name} ({column_name})'
        )
        schema_editor.execute(
            f'ALTER TABLE {table_name} ADD CONSTRAINT {quoted_constraint} '
            f'UNIQUE USING INDEX {quoted_constraint}'
        )

    schema_editor.execute(
        f'CREATE INDEX CONCURRENTLY IF NOT EXISTS {like_index_name} '
        f'ON {table_name} ({column_name} varchar_pattern_ops)'
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('deployments', '0056_workload_guard_mesh_replication_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_service_slug_column,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='service',
                    name='slug',
                    field=models.SlugField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RunPython(
            populate_service_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            cleanup_service_slug_artifacts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    enforce_service_slug_constraints,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='service',
                    name='slug',
                    field=models.SlugField(blank=True, max_length=255, unique=True),
                ),
            ],
        ),
    ]
