# Generated by Django 4.2.28 on 2026-05-02 05:48

import re

from django.db import migrations, models


def _column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor,
            table_name,
        )

    return {
        getattr(column, 'name', column[0])
        for column in description
    }


def ensure_service_slug_column(apps, schema_editor):
    Service = apps.get_model('deployments', 'Service')
    table_name = Service._meta.db_table
    if 'slug' in _column_names(schema_editor, table_name):
        return

    quote_name = schema_editor.quote_name
    schema_editor.execute(
        f'ALTER TABLE {quote_name(table_name)} '
        f'ADD COLUMN {quote_name("slug")} varchar(255) NULL'
    )


def _dedupe_slug(base, used_slugs):
    base = (base or 'service').strip('-')[:255] or 'service'
    slug = base
    counter = 1

    while slug in used_slugs:
        suffix = f'-{counter}'
        slug = f"{base[:255 - len(suffix)].rstrip('-')}{suffix}"
        counter += 1

    used_slugs.add(slug)
    return slug


def _service_slug_base(service):
    raw = service.slug or service.name or ''
    base = re.sub(r'[^a-z0-9]+', '-', raw.lower()).strip('-')
    if base:
        return base

    return str(service.id)[:8] or 'service'


def populate_service_slugs(apps, schema_editor):
    Service = apps.get_model('deployments', 'Service')
    used_slugs = set()

    for service in Service.objects.all().only('id', 'name', 'slug').order_by('id'):
        slug = _dedupe_slug(_service_slug_base(service), used_slugs)
        if service.slug == slug:
            continue

        Service.objects.filter(pk=service.pk).update(slug=slug)


def cleanup_service_slug_artifacts(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    Service = apps.get_model('deployments', 'Service')
    table_name = schema_editor.quote_name(Service._meta.db_table)
    constraint_name = schema_editor.quote_name('deployments_service_slug_key')
    like_index_name = schema_editor.quote_name('deployments_service_slug_6f89c844_like')

    schema_editor.execute(
        f'ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS {constraint_name}'
    )
    schema_editor.execute(f'DROP INDEX IF EXISTS {constraint_name}')
    schema_editor.execute(f'DROP INDEX IF EXISTS {like_index_name}')


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0056_workload_guard_mesh_replication_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    ensure_service_slug_column,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='service',
                    name='slug',
                    field=models.SlugField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RunPython(
            populate_service_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            cleanup_service_slug_artifacts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
