# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0057_service_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedserver",
            name="is_lite_agent",
            field=models.BooleanField(
                default=False,
                help_text="If true, this server is a lightweight node connecting to the Master's DB/Redis.",
            ),
        ),
    ]
