# Generated by Django 4.2.28 on 2026-05-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0058_managedserver_is_lite_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedserver',
            name='provision_status',
            field=models.CharField(choices=[('NONE', 'Not provisioned'), ('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('UPDATING', 'Updating'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='NONE', max_length=20),
        ),
    ]
