# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0059_alter_managedserver_provision_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="remote_deployment_id",
            field=models.CharField(
                blank=True,
                help_text="Deployment ID on a delegated remote server.",
                max_length=64,
                null=True,
            ),
        ),
    ]
