# Generated by Django 4.2.28 on 2026-05-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0060_deployment_remote_deployment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='max_concurrent_builds',
            field=models.PositiveIntegerField(default=1, help_text='Maximum concurrent builds across the entire node fleet (to prevent OOM)'),
        ),
    ]
