# Generated by Django 4.2.28 on 2026-05-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0062_platformupdate_addon_compatibility_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='target_server',
            field=models.ForeignKey(blank=True, help_text='Server this deployment was explicitly routed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_deployments', to='deployments.managedserver'),
        ),
    ]
