# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0063_deployment_target_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='target_is_local',
            field=models.BooleanField(
                default=False,
                help_text='True when this deployment was explicitly routed to the local controller',
            ),
        ),
    ]
