# Generated by Django 5.0.14 on 2026-05-17 13:23

from django.db import migrations, models



def backfill_metadata(apps, schema_editor):
    Service = apps.get_model('deployments', 'Service')
    Deployment = apps.get_model('deployments', 'Deployment')

    # Backfill Service active_host_ip conservatively based on server host/ip
    # Use bulk operations to avoid per-row saves and long-held locks.
    services_with_server = []
    services_local = []
    for service in Service.objects.select_related('server').all().iterator():
        if service.server:
            service.active_host_ip = service.server.private_ip or service.server.host
            service.active_target_type = "remote"
            services_with_server.append(service)
        else:
            service.active_target_type = "local"
            services_local.append(service)

    if services_with_server:
        Service.objects.bulk_update(services_with_server, ['active_host_ip', 'active_target_type'], batch_size=500)
    if services_local:
        Service.objects.bulk_update(services_local, ['active_target_type'], batch_size=500)

    # Backfill Deployment based on related Service (conservative approximation)
    # Use subquery-style updates per target_type to avoid per-row saves.
    deployments_to_update = []
    for deployment in (
        Deployment.objects
        .exclude(status='FAILED')
        .select_related('service')
        .iterator()
    ):
        svc = deployment.service
        if svc and getattr(svc, 'active_target_type', None):
            deployment.verified_target_type = svc.active_target_type
            deployment.verified_host_ip = svc.active_host_ip
            deployments_to_update.append(deployment)

    if deployments_to_update:
        Deployment.objects.bulk_update(
            deployments_to_update,
            ['verified_target_type', 'verified_host_ip'],
            batch_size=500,
        )



class Migration(migrations.Migration):


    dependencies = [
        ("deployments", "0065_reencrypt_transfer_credentials"),
    ]


    operations = [
        migrations.AddField(
            model_name="deployment",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the execution location was verified.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_host_ip",
            field=models.CharField(
                blank=True,
                help_text="The verified IP address or hostname where the deployment executed.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_runtime_id",
            field=models.CharField(
                blank=True,
                help_text="The verified container ID or process ID of the deployment.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_target_type",
            field=models.CharField(
                blank=True,
                help_text="The verified runtime environment where this deployment actually executed.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_host_ip",
            field=models.CharField(
                blank=True,
                help_text="The verified IP address or hostname where the service is executing.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_runtime_id",
            field=models.CharField(
                blank=True,
                help_text="The verified container ID or process ID of the running service.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_target_type",
            field=models.CharField(
                blank=True,
                help_text="The verified runtime environment where this service is actually executing (e.g., 'local', 'remote', 'lite_agent').",
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_metadata, reverse_code=migrations.RunPython.noop),
    ]

