# Generated by Django 5.0.14 on 2026-05-17 13:23

from django.db import migrations, models



def backfill_metadata(apps, schema_editor):
    Service = apps.get_model('deployments', 'Service')
    Deployment = apps.get_model('deployments', 'Deployment')

    # Backfill Service active_host_ip conservatively based on server host/ip
    for service in Service.objects.all():
        if service.server:
            service.active_host_ip = service.server.private_ip or service.server.host
            service.active_target_type = "remote"
            service.save(update_fields=['active_host_ip', 'active_target_type'])
        elif service.is_agent_service:
            service.active_target_type = "lite_agent"
            service.save(update_fields=['active_target_type'])
        else:
            service.active_target_type = "local"
            service.save(update_fields=['active_target_type'])

    # Backfill Deployment based on related Service (conservative approximation)
    for deployment in Deployment.objects.exclude(status='FAILED'):
        if deployment.service.active_target_type:
            deployment.verified_target_type = deployment.service.active_target_type
            deployment.verified_host_ip = deployment.service.active_host_ip
            deployment.save(update_fields=['verified_target_type', 'verified_host_ip'])

class Migration(migrations.Migration):


    dependencies = [
        ("deployments", "0065_reencrypt_transfer_credentials"),
    ]


    operations = [
        migrations.RunPython(backfill_metadata, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="deployment",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the execution location was verified.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_host_ip",
            field=models.CharField(
                blank=True,
                help_text="The verified IP address or hostname where the deployment executed.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_runtime_id",
            field=models.CharField(
                blank=True,
                help_text="The verified container ID or process ID of the deployment.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_target_type",
            field=models.CharField(
                blank=True,
                help_text="The verified runtime environment where this deployment actually executed.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_host_ip",
            field=models.CharField(
                blank=True,
                help_text="The verified IP address or hostname where the service is executing.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_runtime_id",
            field=models.CharField(
                blank=True,
                help_text="The verified container ID or process ID of the running service.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_target_type",
            field=models.CharField(
                blank=True,
                help_text="The verified runtime environment where this service is actually executing (e.g., 'local', 'remote', 'lite_agent').",
                max_length=50,
                null=True,
            ),
        ),
    ]
