# Generated by Django 5.0.14 on 2026-05-17 13:23

from django.db import migrations, models


def backfill_metadata(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor != 'postgresql':
        return

    with conn.cursor() as cursor:
        cursor.execute("""
            UPDATE deployments_service s
            SET active_host_ip = COALESCE(ms.private_ip::text, ms.host),
                active_target_type = 'remote'
            FROM deployments_managedserver ms
            WHERE s.server_id = ms.id
              AND (s.active_host_ip IS NULL OR s.active_target_type IS NULL)
        """)

        cursor.execute("""
            UPDATE deployments_service
            SET active_target_type = 'local'
            WHERE server_id IS NULL
              AND active_target_type IS NULL
        """)

        cursor.execute("""
            UPDATE deployments_deployment d
            SET verified_target_type = s.active_target_type,
                verified_host_ip = s.active_host_ip
            FROM deployments_service s
            WHERE d.service_id = s.id
              AND d.status != 'FAILED'
              AND s.active_target_type IS NOT NULL
              AND (d.verified_target_type IS NULL OR d.verified_host_ip IS NULL)
        """)



class Migration(migrations.Migration):


    dependencies = [
        ("deployments", "0065_reencrypt_transfer_credentials"),
    ]


    operations = [
        migrations.AddField(
            model_name="deployment",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the execution location was verified.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_host_ip",
            field=models.CharField(
                blank=True,
                help_text="The verified IP address or hostname where the deployment executed.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_runtime_id",
            field=models.CharField(
                blank=True,
                help_text="The verified container ID or process ID of the deployment.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="verified_target_type",
            field=models.CharField(
                blank=True,
                help_text="The verified runtime environment where this deployment actually executed.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_host_ip",
            field=models.CharField(
                blank=True,
                help_text="The verified IP address or hostname where the service is executing.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_runtime_id",
            field=models.CharField(
                blank=True,
                help_text="The verified container ID or process ID of the running service.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="active_target_type",
            field=models.CharField(
                blank=True,
                help_text="The verified runtime environment where this service is actually executing (e.g., 'local', 'remote', 'lite_agent').",
                max_length=50,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_metadata, reverse_code=migrations.RunPython.noop),
    ]

