# Generated by Django 4.2.28 on 2026-05-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0067_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('REVIEW', 'Review'), ('BUILDING', 'Building'), ('BUILD_FAILED', 'Build Failed'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('BACKUP_RUNNING', 'Backup Running'), ('BACKUP_FAILED', 'Backup Failed'), ('MIGRATION_PLANNING', 'Migration Planning'), ('MIGRATION_RUNNING', 'Migration Running'), ('MIGRATION_FAILED', 'Migration Failed'), ('DEPLOYING', 'Deploying'), ('HEALTH_CHECK', 'Health Check'), ('TRAFFIC_SHIFTING', 'Traffic Shifting'), ('MONITORING', 'Monitoring'), ('STAGED', 'Staged'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('INACTIVE', 'Inactive'), ('ROLLING_BACK', 'Rolling Back'), ('ROLLED_BACK', 'Rolled Back')], default='QUEUED', max_length=20),
        ),
    ]
