# Generated by Django 4.2.28 on 2026-05-21 16:33

from django.db import migrations


def forward_triggers(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        sql = """
            CREATE OR REPLACE FUNCTION prevent_audit_log_modification()
            RETURNS TRIGGER AS $$
            BEGIN
                IF TG_OP = 'UPDATE' THEN
                    RAISE EXCEPTION 'Audit logs are immutable and cannot be modified.';
                ELSIF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'Audit logs are undeletable.';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER enforce_audit_log_immutability
            BEFORE UPDATE OR DELETE ON deployments_auditlog
            FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_modification();
        """
        schema_editor.execute(sql)
    elif schema_editor.connection.vendor == 'sqlite':
        sql_update = """
            CREATE TRIGGER enforce_audit_log_immutability_update
            BEFORE UPDATE ON deployments_auditlog
            BEGIN
                SELECT RAISE(FAIL, 'Audit logs are immutable and cannot be modified.');
            END;
        """
        sql_delete = """
            CREATE TRIGGER enforce_audit_log_immutability_delete
            BEFORE DELETE ON deployments_auditlog
            BEGIN
                SELECT RAISE(FAIL, 'Audit logs are undeletable.');
            END;
        """
        schema_editor.execute(sql_update)
        schema_editor.execute(sql_delete)

def reverse_triggers(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        sql = """
            DROP TRIGGER IF EXISTS enforce_audit_log_immutability ON deployments_auditlog;
            DROP FUNCTION IF EXISTS prevent_audit_log_modification();
        """
        schema_editor.execute(sql)
    elif schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("DROP TRIGGER IF EXISTS enforce_audit_log_immutability_update;")
        schema_editor.execute("DROP TRIGGER IF EXISTS enforce_audit_log_immutability_delete;")

class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0069_auditlog_project_auditlog_user'),
    ]

    operations = [
        migrations.RunPython(forward_triggers, reverse_triggers)
    ]

