# Generated by Django 4.2.28 on 2026-05-23 13:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deployments', '0071_deployment_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previewenvironment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='previewenvironment',
            name='commit_sha',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='preview_environments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EcosystemPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('deploy_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scanning', 'Scanning'), ('review', 'Ready for Review'), ('deploying', 'Deploying'), ('completed', 'Completed'), ('failed', 'Failed')], default='scanning', max_length=20)),
                ('selected_repos', models.JSONField(blank=True, default=list)),
                ('ai_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('plan', models.JSONField(blank=True, null=True)),
                ('services_created', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecosystem_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='deployments_user_id_52e6e6_idx'), models.Index(fields=['scan_task_id'], name='deployments_scan_ta_04ec97_idx'), models.Index(fields=['deploy_task_id'], name='deployments_deploy__e1904c_idx')],
            },
        ),
    ]
