# Generated by hand for safedeploy rejected_by field

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deployments', '0072_ecosystem_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentapproval',
            name='rejected_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rejected_approvals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
