# Generated by Django 5.0.14 on 2026-05-29 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0077_widen_env_var_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="FVMIPAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Allocated IP address within the FVM supernet",
                        protocol="IPv4",
                        unique=True,
                    ),
                ),
                (
                    "vm_id",
                    models.CharField(
                        help_text="Unique identifier for the VM (e.g., addon container_name or service instance id)",
                        max_length=255,
                    ),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "node",
                    models.ForeignKey(
                        help_text="The server node hosting the VM",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fvm_allocations",
                        to="deployments.managedserver",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked service, if this IP is for a deployed service",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fvm_allocations",
                        to="deployments.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "FVM IP Allocation",
                "ordering": ["ip_address"],
            },
        ),
    ]
