# Generated by Django 5.0.14 on 2026-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0078_fvmipallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="runtime",
            field=models.CharField(
                choices=[("docker", "Docker"), ("firecracker", "Firecracker")],
                default="docker",
                help_text="The container runtime to use for this addon.",
                max_length=20,
            ),
        ),
    ]
