# Generated by Django 5.0.14 on 2026-06-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0084_encrypt_s3_credentials'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicereplica',
            new_name='deployments_service_8a4250_idx',
            old_name='replica_service_status_idx',
        ),
        migrations.RenameIndex(
            model_name='servicereplica',
            new_name='deployments_node_id_c29f06_idx',
            old_name='replica_node_status_idx',
        ),
    ]
