# Add BackupEncryptionKey model for cross-master backup restore.
#
# Each master auto-generates a unique Fernet BACKUP_ENCRYPTION_KEY
# at install time (see install.sh:1605, 4191, 5912). The V2 backup
# header (see backup_service.py) carries a random 4-byte key_id
# and a 4-byte fingerprint. To restore a backup created on a
# different master, the target looks up the source's key by
# key_id in this table. Operators can import the source's
# key material via POST /backups/import-key/.
#
# The key_material field is EncryptedCharField (FIELD_ENCRYPTION_KEY
# at rest) so a raw DB read does not yield decryption capability.

import uuid

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0092_managedserver_tls_verify_and_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupEncryptionKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key_id', models.CharField(
                    db_index=True, max_length=8, unique=True,
                    help_text='4 random bytes as 8-char hex; matches the V2 backup header key_id.',
                )),
                ('fingerprint', models.CharField(
                    db_index=True, max_length=8,
                    help_text='First 4 bytes of SHA-256(raw_key) as 8-char hex; matches V2 header fingerprint.',
                )),
                ('key_material_encrypted', encrypted_model_fields.fields.EncryptedCharField(
                    max_length=512,
                    help_text='Fernet BACKUP_ENCRYPTION_KEY, encrypted at rest with FIELD_ENCRYPTION_KEY.',
                )),
                ('label', models.CharField(
                    blank=True, default='', max_length=100,
                    help_text='Operator label e.g. "master-a-imported-2026-06-14".',
                )),
                ('source', models.CharField(
                    choices=[
                        ('AUTO', 'Auto-generated by this master'),
                        ('IMPORTED', 'Imported from another master'),
                    ],
                    default='AUTO', max_length=20,
                )),
                ('is_active', models.BooleanField(
                    default=True,
                    help_text='True for the row matching the current BACKUP_ENCRYPTION_KEY env var.',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backupencryptionkey',
            index=models.Index(
                fields=['fingerprint', 'is_active'],
                name='deployments__fingerp_idx',
            ),
        ),
    ]
