# Generated by Django 5.0.14 on 2026-06-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0102_deploymentartifact_is_archived'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='addon',
            name='uniq_addon_service_public_domain',
        ),
        migrations.RemoveConstraint(
            model_name='reservedsubdomain',
            name='unique_active_reservedsubdomain_subdomain',
        ),
        migrations.RenameIndex(
            model_name='backupencryptionkey',
            new_name='deployments_fingerp_107a94_idx',
            old_name='deployments__fingerp_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdelivery',
            new_name='deployments_provide_1b4d19_idx',
            old_name='deployments_prov_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='health_webhook_token_last_used_at',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='green_container_id',
            field=models.CharField(blank=True, help_text='Temp container ID for the new version during blue-green swap', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='tls_cert_sha256',
            field=models.CharField(blank=True, default='', help_text="Optional SHA-256 fingerprint of the server's TLS cert (hex, no colons). When set, connections are pinned to this cert regardless of the system trust store.", max_length=64),
        ),
        migrations.AlterField(
            model_name='reservedsubdomain',
            name='subdomain',
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='servertransfer',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('UPLOADING', 'Uploading'), ('RESTORING', 'Restoring'), ('DNS_CUTOVER', 'DNS Cutover'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=20),
        ),
    ]
