# Generated by Django 5.0.14 on 2026-06-17 23:15

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0103_remove_addon_uniq_addon_service_public_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='bitbucket_webhook_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Bitbucket webhook secret for push event verification'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='github_webhook_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='GitHub webhook secret for push event verification'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='gitlab_webhook_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='GitLab webhook secret for push event verification'),
        ),
    ]
