# Generated by Django 5.0.14 on 2026-06-17 23:43

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0104_add_webhook_secrets_to_platformconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='caddy_ask_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Caddy on_demand_tls ask shared secret. Set via UI — if empty, falls back to CADDY_ASK_SECRET env var. A random ephemeral value is generated on each restart if neither is configured.'),
        ),
    ]
