# Generated by Django 5.0.14 on 2026-06-18 01:35

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0105_add_caddy_ask_secret_to_platformconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managedserver',
            name='hardware_fingerprint',
            field=models.JSONField(blank=True, default=dict, help_text='Captured hardware identifiers collected during provisioning (CPU serial, DMI UUID, MAC addresses, disk serials). Used for node identity attestation — verifies the same hardware is connecting.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='recovery_phrase_hash',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='SHA-256 hash of the 12-word recovery phrase (salted). Used as last-resort admin account access if all trusted devices are lost.'),
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='Cryptographically random token stored in browser localStorage', max_length=128, unique=True)),
                ('fingerprint_hash', models.CharField(db_index=True, help_text='SHA-256 hash of combined hardware/software fingerprint signals', max_length=128)),
                ('fingerprint_data', models.JSONField(blank=True, default=dict, help_text='Raw fingerprint signals (canvas hash, WebGL, audio, fonts, CPU, GPU, etc.)')),
                ('trust_method', models.CharField(choices=[('browser', 'Browser fingerprint'), ('ssh_key', 'SSH public key'), ('api_token', 'API token'), ('manual', 'Manually approved')], default='browser', help_text='How this device was enrolled', max_length=32)),
                ('ssh_key_fingerprint', models.CharField(blank=True, default='', help_text='SHA-256 fingerprint of SSH public key (for SSH trust method)', max_length=128)),
                ('label', models.CharField(blank=True, default='', help_text="User-assigned label (e.g. 'Work Laptop', 'iPhone')", max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at time of enrollment', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User-Agent string at time of enrollment')),
                ('trust_score', models.IntegerField(default=0, help_text='Aggregated trust score (0-100). Incremented on successful interactions, decremented on suspicious activity.')),
                ('trust_score_updated_at', models.DateTimeField(blank=True, help_text='Last time the trust score was modified.', null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
