# Generated by Django 5.0.14 on 2026-06-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0110_service_auto_rollback_config'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='managedserver',
            name='deployments_lite_ready_idx',
        ),
        migrations.RemoveIndex(
            model_name='managedserver',
            name='deployments_last_ag_idx',
        ),
    ]
