# Generated by Django 5.0.14 on 2026-06-23 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0111_remove_managedserver_deployments_lite_ready_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', help_text='Optional human label e.g. "before Redis upgrade"', max_length=255)),
                ('trigger', models.CharField(choices=[('MANUAL', 'Manual'), ('PRE_DEPLOY', 'Pre-Deploy'), ('PRE_ENV_CHANGE', 'Pre-Env Change'), ('SCHEDULED', 'Scheduled')], default='MANUAL', max_length=20)),
                ('config_data', models.JSONField(default=dict, help_text='Full config payload: env_vars, deploy_type, docker_image, repository_url, branch, public_domain, resources, replicas, addons, build/start commands, health check, etc.')),
                ('diff_summary', models.JSONField(blank=True, default=None, help_text='Computed diff from parent snapshot (added/removed/changed keys).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_snapshot', models.ForeignKey(blank=True, help_text='Previous snapshot in the diff chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='deployments.servicesnapshot')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='deployments.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', '-created_at'], name='deployments_service_bf4bea_idx')],
            },
        ),
    ]
