# Generated by Django 5.0.14 on 2026-06-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0113_ecosystemplan_scan_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverbackup',
            name='cloud_bucket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serverbackup',
            name='cloud_key',
            field=models.CharField(blank=True, default='', help_text='S3 object key, e.g. smsly-backups/<scope>/<filename>', max_length=1024),
        ),
        migrations.AddField(
            model_name='serverbackup',
            name='cloud_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebackup',
            name='cloud_bucket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicebackup',
            name='cloud_key',
            field=models.CharField(blank=True, default='', help_text='S3 object key, e.g. smsly-backups/<service>/<filename>', max_length=1024),
        ),
        migrations.AddField(
            model_name='servicebackup',
            name='cloud_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
