# Generated by Django 5.0.14 on 2026-06-28 13:07

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0115_platformconfig_ecosystem_build_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='cloud_destination',
            field=models.ForeignKey(blank=True, help_text='Optional cloud storage destination to upload cron execution logs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cron_jobs', to='deployments.cloudstoragedestination'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='alert_phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number for deployment failure alerts (E.164 format)', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='billing_currency',
            field=models.CharField(blank=True, default='USD', help_text='Billing currency code (e.g. USD, NGN)', max_length=10),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='billing_pro_amount',
            field=models.CharField(blank=True, default='29.00', help_text='Pro plan amount (e.g. 29.00)', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='billing_pro_period_days',
            field=models.PositiveIntegerField(default=30, help_text='Pro plan billing period in days'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='container_registry_url',
            field=models.CharField(blank=True, default='127.0.0.1:5000', help_text='Container registry URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='critical_alert_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number for critical/P0 voice call alerts', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='ecosystem_build_stagger_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Seconds between each build start within an ecosystem wave'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='ecosystem_max_concurrent_builds',
            field=models.PositiveIntegerField(default=2, help_text='Maximum concurrent ecosystem builds'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='enable_legacy_tunnel_api',
            field=models.BooleanField(default=False, help_text='Enable legacy function-based tunnel API'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='notify_on_success',
            field=models.BooleanField(default=False, help_text='Enable SMS on successful deployments'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='registry_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Container registry password'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='registry_user',
            field=models.CharField(blank=True, default='smsly-registry', help_text='Container registry username', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='sentry_dsn',
            field=models.CharField(blank=True, default='', help_text='Sentry DSN for error tracking', max_length=300),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='sentry_environment',
            field=models.CharField(blank=True, default='production', help_text='Sentry environment name', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='sentry_profiles_sample_rate',
            field=models.FloatField(default=0.0, help_text='Sentry profiles sample rate (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='sentry_traces_sample_rate',
            field=models.FloatField(default=0.0, help_text='Sentry traces sample rate (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='smsly_disable_tier_gates',
            field=models.BooleanField(default=True, help_text='Disable billing tier gates (allow all features)'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='smsly_internal_api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Internal service-to-service API key'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='smsly_platform_api_url',
            field=models.URLField(blank=True, default='http://smsly-platform-api:8000/api/v1', help_text='SMSLY Platform API internal URL', max_length=300),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='smsly_sms_api_url',
            field=models.URLField(blank=True, default='http://smsly-sms:8000/api/v1', help_text='SMSLY SMS API internal URL', max_length=300),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='smsly_strict_ssh_host_key_check',
            field=models.BooleanField(default=False, help_text='Strict SSH host-key verification for provisioner'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='smsly_voice_api_url',
            field=models.URLField(blank=True, default='http://smsly-voice:8000/api/v1', help_text='SMSLY Voice API internal URL', max_length=300),
        ),
    ]
