# Generated by Django 5.0.14 on 2026-06-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0116_cronjob_cloud_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverbackup',
            name='cloud_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployments.cloudstoragedestination'),
        ),
        migrations.AddField(
            model_name='servicebackup',
            name='cloud_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployments.cloudstoragedestination'),
        ),
    ]
