# Generated by Django 5.0.14 on 2026-06-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0117_serverbackup_cloud_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_expression', models.CharField(default='0 3 * * *', max_length=100)),
                ('retention_days', models.IntegerField(default=7)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(null=True)),
                ('next_run', models.DateTimeField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_schedules', to='deployments.service')),
            ],
        ),
    ]
