# Generated by Django 5.0.14 on 2026-06-28 13:24

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0118_snapshotschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesnapshot',
            name='cloud_bucket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicesnapshot',
            name='cloud_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deployments.cloudstoragedestination'),
        ),
        migrations.AddField(
            model_name='servicesnapshot',
            name='cloud_key',
            field=models.CharField(blank=True, default='', help_text='S3 object key, e.g. smsly-snapshots/<service>/<filename>', max_length=1024),
        ),
        migrations.AddField(
            model_name='servicesnapshot',
            name='cloud_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snapshotschedule',
            name='is_server_wide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snapshotschedule',
            name='s3_access_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='snapshotschedule',
            name='s3_bucket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='snapshotschedule',
            name='s3_endpoint',
            field=models.CharField(blank=True, default='', help_text='Custom endpoint for R2/MinIO. Leave blank for AWS S3.', max_length=500),
        ),
        migrations.AddField(
            model_name='snapshotschedule',
            name='s3_region',
            field=models.CharField(blank=True, default='us-east-1', max_length=100),
        ),
        migrations.AddField(
            model_name='snapshotschedule',
            name='s3_secret_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='snapshotschedule',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Local'), ('s3', 'S3 / R2 / MinIO')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='snapshotschedule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_schedules', to='deployments.service'),
        ),
    ]
