# Generated by Django 5.0.14 on 2026-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0119_servicesnapshot_cloud_bucket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupschedule',
            name='db_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverbackup',
            name='db_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicebackup',
            name='db_only',
            field=models.BooleanField(default=False),
        ),
    ]
