# Generated by Django 5.0.14 on 2026-06-28 19:42

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0120_backupschedule_db_only_serverbackup_db_only_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('dockerhub', 'Docker Hub'), ('ghcr', 'GitHub Container Registry'), ('ecr', 'AWS ECR'), ('gcr', 'Google Container Registry'), ('acr', 'Azure Container Registry'), ('custom', 'Custom Registry')], default='custom', max_length=30)),
                ('registry_url', models.CharField(help_text='e.g. ghcr.io, 123456.dkr.ecr.us-east-1.amazonaws.com', max_length=500)),
                ('username', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('password', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Token, PAT, or password')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='registry_credential',
            field=models.ForeignKey(blank=True, help_text='Private registry credentials for image pulls', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='deployments.registrycredential'),
        ),
    ]
