# Generated by Django 5.0.14 on 2026-06-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0121_registry_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='enable_crowdsec_waf',
            field=models.BooleanField(default=False, help_text='Enable CrowdSec WAF to block malicious traffic automatically'),
        ),
    ]
