# Generated by Django 5.0.14 on 2026-06-29 22:49

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('deployments', '0122_platform_config_crowdsec'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='registry_override',
            field=models.JSONField(blank=True, help_text='Per-deployment registry override {url, username, password} — builder uses this instead of the scoped chain', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_ephemeral',
            field=models.BooleanField(default=False, help_text='Auto-created for custom-registry deploy; hidden from default project list'),
        ),
        migrations.CreateModel(
            name='ScopedRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('registry_url', models.CharField(blank=True, default='', help_text='e.g. registry.example.com:5000 or 127.0.0.1:5000', max_length=255)),
                ('username', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('password', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('is_internal', models.BooleanField(default=False, help_text='If True, this is a platform-internal registry reachable via the mesh VPN')),
                ('allowed_registry_hosts', models.JSONField(blank=True, default=list, help_text='Additional registry hosts allowed for this scope (appended to platform-wide allowlist)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['organization', 'team', 'project']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Scoped Registry',
                'verbose_name_plural': 'Scoped Registries',
            },
        ),
        migrations.AddField(
            model_name='managedserver',
            name='registry_access',
            field=models.ManyToManyField(blank=True, help_text='Registries this node can authenticate with for image pulls/deployments', to='deployments.scopedregistry'),
        ),
        migrations.AddIndex(
            model_name='scopedregistry',
            index=models.Index(fields=['content_type', 'object_id'], name='deployments_content_50dad4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scopedregistry',
            unique_together={('content_type', 'object_id')},
        ),
    ]
