# Generated by Django 5.0.14 on 2026-06-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0123_scoped_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverbackup',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Human-readable label for quick identification', max_length=255),
        ),
        migrations.AddField(
            model_name='servicebackup',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Human-readable label for quick identification, e.g. "Pre-upgrade backup" or "Cloud restore"', max_length=255),
        ),
    ]
