# Generated by Django 5.0.14 on 2026-06-30 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0125_schedule_cloud_upload_toggle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='allowed_actions',
            field=models.JSONField(blank=True, default=list, help_text='Explicitly allowed permission codes — if set, overrides role-based checks'),
        ),
        migrations.AddField(
            model_name='service',
            name='locked',
            field=models.BooleanField(default=False, help_text='Deployment lock — blocks deploys and destructive writes'),
        ),
        migrations.AddField(
            model_name='service',
            name='locked_reason',
            field=models.TextField(blank=True, default='', help_text='Why this service is locked (shown in UI)'),
        ),
        migrations.AddField(
            model_name='service',
            name='restrict_to_creator',
            field=models.BooleanField(default=False, help_text='Only the owner can modify this service'),
        ),
        migrations.AddField(
            model_name='service',
            name='restricted_environments',
            field=models.JSONField(blank=True, default=list, help_text="List of allowed deployment target environments (e.g. ['production', 'staging'])"),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=list, help_text='Custom permission code overrides for this member at the project level. If set, these replace the default role + team permissions.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, membership automatically expires after this date', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='deployments.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'ordering': ['-joined_at'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
