# Generated by Django 5.0.14 on 2026-06-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0126_service_allowed_actions_service_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverbackup',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional metadata: cloud_upload_error, checksums, etc.'),
        ),
    ]
