# Generated by Django 5.0.14 on 2026-06-30 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0127_add_server_backup_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverbackup',
            name='metadata',
        ),
        migrations.AddField(
            model_name='ecosystemplan',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this ecosystem plan belongs to. All created services are scoped to this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecosystem_plans', to='deployments.project'),
        ),
        migrations.AddIndex(
            model_name='ecosystemplan',
            index=models.Index(fields=['project', 'status'], name='deployments_project_1cc7f4_idx'),
        ),
    ]
