# Generated by Django 5.0.14 on 2026-07-01 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('deployments', '0128_add_ecosystem_plan_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverbackup',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional metadata: cloud_upload_error, checksums, etc.'),
        ),
        migrations.CreateModel(
            name='ScopedNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('network_name', models.CharField(blank=True, default='', help_text='Docker network name. Leave blank to inherit from parent scope.', max_length=255)),
                ('driver', models.CharField(default='bridge', help_text='Docker network driver (bridge, overlay, macvlan, etc.)', max_length=50)),
                ('isolated', models.BooleanField(default=False, help_text='If True, containers under this scope get a dedicated isolated network that prevents cross-scope communication')),
                ('internal', models.BooleanField(default=False, help_text='If True, the network has no external connectivity (--internal)')),
                ('enable_ipv6', models.BooleanField(default=False, help_text='Enable IPv6 on the network')),
                ('subnet', models.CharField(blank=True, default='', help_text='Custom subnet CIDR (auto-assigned if blank)', max_length=43)),
                ('allow_public_traefik', models.BooleanField(default=True, help_text='If False, containers on this network are NOT exposed via Traefik (internal-only, even for services with public domains)')),
                ('allowed_egress_networks', models.JSONField(blank=True, default=list, help_text='List of CIDR ranges containers on this network can reach. Empty = unrestricted egress.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['organization', 'team', 'project']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Scoped Network',
                'verbose_name_plural': 'Scoped Networks',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='deployments_content_b8f75f_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
