# Generated by Django 5.0.14 on 2026-07-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0129_add_server_backup_metadata_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='trivy_enabled',
            field=models.BooleanField(default=True, help_text='Enable Trivy container image vulnerability scanning on build'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='trivy_fail_on_severity',
            field=models.CharField(default='CRITICAL', help_text='Minimum severity that blocks the build: LOW, MEDIUM, HIGH, CRITICAL', max_length=16),
        ),
    ]
