# Generated by Django 5.0.14 on 2026-07-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0136_add_servicetrafficlog'),
        ('deployments', '0139_bundle_model_refinements'),
    ]

    operations = [
    ]
