# Generated by Django 5.0.14 on 2026-07-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0140_merge_20260708_0229'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicetrafficlog',
            new_name='deployments_service_991d77_idx',
            old_name='deployments_service_country_code_idx',
        ),
        migrations.RenameIndex(
            model_name='servicetrafficlog',
            new_name='deployments_ip_addr_dc57c7_idx',
            old_name='deployments_ip_address_idx',
        ),
        migrations.RenameIndex(
            model_name='servicetrafficlog',
            new_name='deployments_geo_res_ac07d8_idx',
            old_name='deployments_geo_resolved_idx',
        ),
        migrations.RenameIndex(
            model_name='servicetrafficlog',
            new_name='deployments_last_se_76ce14_idx',
            old_name='deployments_last_seen_idx',
        ),
    ]
