# Generated by Django 5.0.14 on 2026-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0143_ecosystemplan_cancel_others_and_per_addon_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecosystemplan',
            name='shared_addon_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-addon sharing configuration. Keys are addon types (e.g. "POSTGRES", "REDIS"), values are objects with "shared" (bool) and optionally "shared_by" (list of service names). When an addon is not listed, the use_shared_addons default applies.'),
        ),
    ]
