# Generated by Django 5.0.14 on 2026-07-11 01:08

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0149_reset_auditlog_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='mapbox_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Mapbox GL token for the traffic world map on the Metrics page. Falls back to NEXT_PUBLIC_MAPBOX_TOKEN env var if empty. Can be left empty to use free OpenFreeMap tiles (no token needed).'),
        ),
    ]
