# Generated by Django 5.0.14 on 2026-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0150_alter_platformconfig_mapbox_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedserver',
            name='node_type',
            field=models.CharField(choices=[('master', 'Master (full stack)'), ('node', 'Node (full stack, no Caddy)'), ('agent-lite', 'Agent Lite (minimal)'), ('media', 'Media Node (voice + video baremetal)')], default='agent-lite', help_text='Determines provisioning mode and available services.', max_length=20),
        ),
    ]
