# Generated by Django 5.0.14 on 2026-07-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0152_githubappinstallation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='githubappinstallation',
            new_name='deployments_user_id_0ad2ba_idx',
            old_name='idx_github_install_user_status',
        ),
        migrations.RenameIndex(
            model_name='githubappinstallation',
            new_name='deployments_organiz_0df9ec_idx',
            old_name='idx_github_install_org_status',
        ),
        migrations.RenameIndex(
            model_name='githubappinstallation',
            new_name='deployments_account_270407_idx',
            old_name='idx_github_install_account',
        ),
    ]
