# Generated by Django 5.0.14 on 2026-07-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0153_rename_idx_github_install_user_status_deployments_user_id_0ad2ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='autoscale_enabled',
            field=models.BooleanField(null=True, help_text='Master toggle for horizontal autoscaling. When disabled, the service will not be auto-scaled regardless of other settings.'),
        ),
    ]
