# Generated by Django 5.0.14 on 2026-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0154_service_autoscale_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='autoscale_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle for horizontal autoscaling. When disabled, the service will not be auto-scaled regardless of other settings.', null=True),
        ),
    ]
