# Generated by Django 5.0.14 on 2026-07-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0159_github_deployments_watchpaths_bot_pr"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deploymentapproval",
            new_name="deployapproval_svc_status_idx",
            old_name="deployapproval_service_status_idx",
        ),
        migrations.RemoveField(
            model_name="service",
            name="safe_deploy_enabled",
        ),
        migrations.AlterField(
            model_name="previewenvironment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("BUILDING", "Building"),
                    ("BUILD_FAILED", "Build Failed"),
                    ("PROVISIONING", "Provisioning"),
                    ("DB_CLONE_CREATING", "DB Clone Creating"),
                    ("DB_CLONE_FAILED", "DB Clone Failed"),
                    ("MIGRATION_RUNNING", "Migration Running"),
                    ("MIGRATION_FAILED", "Migration Failed"),
                    ("TESTS_RUNNING", "Tests Running"),
                    ("TESTS_FAILED", "Tests Failed"),
                    ("HEALTH_CHECK_RUNNING", "Health Check Running"),
                    ("HEALTH_CHECK_FAILED", "Health Check Failed"),
                    ("READY", "Ready"),
                    ("EXPIRED", "Expired"),
                    ("DESTROYING", "Destroying"),
                    ("DESTROY_FAILED", "Destroy Failed"),
                    ("DESTROYED", "Destroyed"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
