# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0160_rename_deployapproval_service_status_idx_deployapproval_svc_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='autoscale_enabled',
            field=models.BooleanField(
                blank=True,
                null=True,
                help_text='Master toggle for horizontal autoscaling. When disabled, '
                          'the service will not be auto-scaled regardless of other settings. '
                          'NULL/None is treated as enabled by autoscaling query filters.',
            ),
        ),
    ]
