# Generated by Django 5.0.14 on 2026-08-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0163_merge_20260811_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='allow_insecure_inter_node_tls',
            field=models.BooleanField(default=False, help_text='Skip TLS verification for inter-node HTTP (dev only)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='api_rate_limit',
            field=models.PositiveIntegerField(default=10000, help_text='Per-IP per-minute API rate limit'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='api_rate_limit_fail_closed',
            field=models.BooleanField(default=False, help_text='Fail closed if rate-limit check errors'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='caddy_daily_cert_cap',
            field=models.PositiveIntegerField(default=20, help_text='Per-apex daily cap for new TLS certificate issuance'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='django_log_level',
            field=models.CharField(default='INFO', help_text='Django log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)', max_length=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='grid_allow_control_plane_workloads',
            field=models.BooleanField(default=True, help_text='Allow user workloads on the control-plane / primary node'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='max_upload_size',
            field=models.PositiveIntegerField(default=104857600, help_text='Maximum upload size in bytes (default 100 MB)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='node_min_free_ram_pct',
            field=models.PositiveIntegerField(default=20, help_text='Minimum free RAM percentage on a node before refusing to spawn a replica'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='node_scorer_min_score',
            field=models.PositiveIntegerField(default=20, help_text='Minimum weighted resource score (0-100) for a node to be accepted for spawning. Composite of 40% free mem + 40% free CPU + 20% free disk.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='scale_cooldown_min',
            field=models.PositiveIntegerField(default=5, help_text='Minimum minutes between consecutive scale-up operations'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='scale_cpu_high',
            field=models.PositiveIntegerField(default=80, help_text='CPU usage percentage above which a new replica is spawned'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='scale_max_replicas',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of replica containers allowed per service'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='smsly_disable_signature_check',
            field=models.BooleanField(default=False, help_text='Globally disable HMAC signature verification (not recommended)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='smsly_max_file_read_size',
            field=models.PositiveIntegerField(default=10485760, help_text='Max file size for container file_read (default 10 MB)'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('REVIEW', 'Review'), ('BUILDING', 'Building'), ('BUILD_FAILED', 'Build Failed'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('BACKUP_RUNNING', 'Backup Running'), ('BACKUP_FAILED', 'Backup Failed'), ('MIGRATION_PLANNING', 'Migration Planning'), ('MIGRATION_RUNNING', 'Migration Running'), ('MIGRATION_FAILED', 'Migration Failed'), ('DEPLOYING', 'Deploying'), ('HEALTH_CHECK', 'Health Check'), ('HEALTH_CHECK_FAILED', 'Health Check Failed'), ('STAGED', 'Staged'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('INACTIVE', 'Inactive'), ('ROLLING_BACK', 'Rolling Back'), ('ROLLED_BACK', 'Rolled Back')], default='QUEUED', max_length=20),
        ),
    ]
