# Generated by Django 5.0.14 on 2026-08-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0165_allow_min_replicas_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='staging_domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='autoscale_cpu_target',
            field=models.IntegerField(default=80, help_text='Target CPU utilization percentage for the autoscaler'),
        ),
    ]
