# Generated by Django 5.0.14 on 2026-08-15 04:15

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0166_add_staging_domain_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedserver',
            name='ssh_key_passphrase',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Passphrase for the encrypted ssh_key (if any). Encrypted at rest.'),
        ),
    ]
