# Generated by Django 5.0.14 on 2026-08-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0167_managedserver_ssh_key_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedserver',
            name='node_components',
            field=models.JSONField(blank=True, default=dict, help_text='Optional components enabled on this node. Keys: observability (cadvisor/node-exporter/docker-labels/promtail), security (fail2ban/ufw/apparmor/auditd/kernel/gvisor), crowdsec, falco.'),
        ),
    ]
