# Generated by Django 5.0.14 on 2026-08-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0169_add_mesh_listen_port_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='rollback_grace_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Minutes to preserve rollback backup containers before the stale scanner removes them. Set to 0 to disable grace period (rollback containers cleaned immediately after promote).'),
        ),
        migrations.AlterField(
            model_name='managedserver',
            name='node_components',
            field=models.JSONField(blank=True, default=dict, help_text='Optional components enabled on this node. Keys: observability (cadvisor/node-exporter/docker-labels/promtail), security (fail2ban/ufw/apparmor/auditd/kernel/gvisor), crowdsec, falco, spire (spire-agent, spire-agent-ecosystem).'),
        ),
    ]
