# Generated by Django 5.0.14 on 2026-08-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0175_fix_url_toggle_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='env_scan_depth',
            field=models.CharField(choices=[('shallow', 'Shallow (.env files only)'), ('standard', 'Standard (.env + config files)'), ('deep', 'Deep (full codebase scan)')], default='standard', help_text='How deeply to scan the repository for environment variables during deployment analysis', max_length=20),
        ),
    ]
