# Generated by Django 5.0.14 on 2026-08-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0176_add_env_scan_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='ai_resources',
            field=models.JSONField(blank=True, default=dict, help_text='AI resource recommendations {cpu_cores, memory_mb} from analysis phase'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='scan_depth',
            field=models.CharField(blank=True, choices=[('shallow', 'Shallow'), ('standard', 'Standard'), ('deep', 'Deep')], default='standard', help_text='Scan depth override for this deployment (empty = use service default)', max_length=20),
        ),
    ]
