# Generated by Django 5.0.14 on 2026-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0177_deployment_ai_resources_deployment_scan_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='default_env_scan_depth',
            field=models.CharField(choices=[('shallow', 'Shallow'), ('standard', 'Standard'), ('deep', 'Deep')], default='shallow', help_text='Default environment scan depth for new services and ecosystem deploys', max_length=20),
        ),
    ]
