# Generated by Django 5.0.14 on 2026-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0186_platformconfig_github_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='db_ha_enabled',
            field=models.BooleanField(default=True, help_text='Enable PostgreSQL read replica for high availability and read scaling.'),
        ),
    ]
