# Generated by Django 5.0.14 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0187_db_ha_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='mtls_enabled',
            field=models.BooleanField(default=False, help_text='Enable SPIFFE mTLS for platform services. Requires platform SPIRE infrastructure to be deployed.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='mtls_ecosystem_enabled',
            field=models.BooleanField(default=False, help_text='Enable SPIFFE mTLS for user-deployed services. Requires ecosystem SPIRE infrastructure to be deployed.'),
        ),
    ]
