# Generated by Django 5.0.14 on 2026-09-02 14:32

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0195_edge_proxy_wildcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='media_repo_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Custom scoped token to clone the media repo'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='media_repo_url',
            field=models.CharField(blank=True, default='', help_text='URL of the Git repository containing media provisioning scripts/code (e.g. Github/Gitlab)', max_length=512),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='default_internal_subnet',
            field=models.CharField(blank=True, default='172.30.224.0/24', help_text="Default Docker bridge subnet (CIDR) for new ecosystem projects' scoped networks. 172.30.0.0/16 is the IETF CGNAT range and doesn't collide with typical LANs. Override at the project level via Project.internal_subnet.", max_length=64),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='edge_proxy_wildcards',
            field=models.BooleanField(default=False, help_text='Edge Shield: ALSO proxy wildcard records (*.domain). DANGEROUS for third-level wildcards (*.grid.example.com) — Cloudflare Universal SSL does not cover them and every deployed service gets ERR_SSL_VERSION_OR_CIPHER_MISMATCH. Only enable if every wildcard is second-level under the zone apex AND you use Advanced Certificates.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='internal_subnet',
            field=models.CharField(blank=True, default='', help_text="Docker bridge subnet (CIDR) for this project's scoped network. When empty, falls back to PlatformConfig.default_internal_subnet (default 172.30.224.0/24). Example: 10.99.0.0/24 for an isolated team bridge.", max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='platform_internal_ip',
            field=models.GenericIPAddressField(blank=True, help_text="Auto-populated at spawn time: this service's IP on the platform-wide shared bridge. Use it for inter-service traffic that needs to escape the project's scope. Empty when use_internal_network=False.", null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='preview_password',
            field=models.CharField(blank=True, default='', help_text="Basic-auth password gating this service's preview URLs", max_length=64),
        ),
    ]
