# Generated by Django 5.0.14 on 2026-09-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0201_ecosystem_wave_recheck_30_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='service_ha_enabled',
            field=models.BooleanField(default=False, help_text="Master toggle for the Service HA manager (beat task, 60s). When enabled, services with ha_mode != 'none' get automated replica/node failover. Individual services opt in via their ha_mode field: 'local' = same-node replicas, 'remote' = cross-node failover."),
        ),
        migrations.AlterField(
            model_name='service',
            name='ha_mode',
            field=models.CharField(choices=[('none', 'No HA'), ('local', 'Local HA (same-node replicas)'), ('remote', 'Remote HA (cross-node failover)')], default='none', help_text='High-availability mode. none = no HA. local = multiple replicas on the same node (fast failover, survives container crashes). remote = replica on a different node (survives node failure — disk, kernel, network, power).', max_length=20),
        ),
    ]
