# Generated by Django 5.0.14 on 2026-09-05 22:50

import apps.deployments.models.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0202_alter_platformconfig_service_ha_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cpu_cores',
            field=models.DecimalField(decimal_places=2, default=apps.deployments.models.service.default_service_cpu_cores, max_digits=6),
        ),
        migrations.AlterField(
            model_name='service',
            name='memory_mb',
            field=models.IntegerField(default=apps.deployments.models.service.default_service_memory_mb),
        ),
    ]
