# Generated by Django 5.0.14 on 2026-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0205_enable_mtls_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='mtls_ecosystem_enabled',
            field=models.BooleanField(default=True, help_text='Enable SPIFFE mTLS for user-deployed services. Requires ecosystem SPIRE infrastructure to be deployed.'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='mtls_enabled',
            field=models.BooleanField(default=True, help_text='Enable SPIFFE mTLS for platform services. Requires platform SPIRE infrastructure to be deployed.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='node_url_enabled',
            field=models.BooleanField(blank=True, default=True, help_text='Enable the direct node URL (e.g. service.grid-node1.smsly.cloud)', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='wildcard_url_enabled',
            field=models.BooleanField(blank=True, default=True, help_text='Enable the master-proxied wildcard URL (e.g. service.grid.smsly.cloud)', null=True),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(condition=models.Q(('commit_hash', 'ecosystem-deploy')), fields=('service', 'commit_hash'), name='uniq_ecosystem_deployment_per_service'),
        ),
    ]
