# Generated by Django 5.0.14 on 2026-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0206_alter_platformconfig_mtls_ecosystem_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystemplan',
            name='services_status',
            field=models.JSONField(blank=True, default=dict, help_text='Map of service name -> current Deployment.status for lifecycle display.'),
        ),
    ]
