import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0212_crowdsec_first_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='crowdsec_cf_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Push CrowdSec bans to Cloudflare (account-level IP lists). Requires an API token + account ID below.',
            ),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='crowdsec_cf_api_token',
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                default='',
                help_text='Cloudflare custom API token with account Firewall/IP List write access.',
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='crowdsec_cf_account_id',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Cloudflare account ID (32 hex chars).',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='crowdsec_cf_action',
            field=models.CharField(
                default='block',
                help_text="Cloudflare remediation: 'block' or 'managed_challenge'.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='crowdsec_cf_bouncer_key',
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                default='',
                help_text='LAPI key for the cloudflare-bouncer (auto-generated by the installer if empty).',
                max_length=256,
            ),
        ),
    ]
