# Generated by Django 5.0.14 on 2026-09-15 23:39

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0214_autoscale_headroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='crowdsec_cf_account_id',
            field=models.CharField(blank=True, default='', help_text='Cloudflare account ID (32 hex chars, from the dashboard URL). Falls back to CROWDSEC_CF_ACCOUNT_ID env var.', max_length=64),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='crowdsec_cf_action',
            field=models.CharField(default='block', help_text="Cloudflare remediation for pushed bans: 'block' drops at the edge (harshest), 'managed_challenge' issues an interactive challenge.", max_length=32),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='crowdsec_cf_api_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Cloudflare custom API token with account Firewall/IP List write access. Falls back to CROWDSEC_CF_API_TOKEN env var if empty.'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='crowdsec_cf_bouncer_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='LAPI key for the cloudflare-bouncer (auto-generated by the installer into CROWDSEC_CF_BOUNCER_KEY if empty).'),
        ),
    ]
