# Generated by Django 5.0.14 on 2026-09-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0215_alter_platformconfig_crowdsec_cf_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='promote_block_contract_unsafe',
            field=models.BooleanField(default=False, help_text="Block promotion when the commit's migrations are contract-unsafe (post-promote rollback would be impossible). Off by default — warns instead."),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='promote_block_when_canary_active',
            field=models.BooleanField(default=False, help_text='Block promotion while a shared-DB canary split is active (canary_percentage > 0). Forces an explicit ramp-to-100 or abort first.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='promote_min_staging_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Minimum seconds a deployment must sit STAGED before it may promote (soak time for staging review; 0 = no soak).'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='promote_require_approval_high_critical',
            field=models.BooleanField(default=True, help_text='Block promotion of HIGH/CRITICAL-risk migrations without an APPROVED DeploymentApproval.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='promote_require_green_healthy',
            field=models.BooleanField(default=True, help_text='Block promotion while the green container is missing, stopped, or unhealthy (local targets only — remote/lite targets cannot be inspected from here and warn instead).'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='promote_require_migration_passed',
            field=models.BooleanField(default=False, help_text='Block promotion unless the deployment commit has a PASSED MigrationValidation. Off by default (warn-only) so non-Django services are unaffected.'),
        ),
        migrations.AddField(
            model_name='service',
            name='promotion_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Per-service overrides for STAGED → ACTIVE promotion readiness (see PlatformConfig promote_* defaults).'),
        ),
    ]
