# Generated by Django 5.0.14 on 2026-09-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0216_promotion_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='promote_canary_get_only',
            field=models.BooleanField(default=False, help_text='Restrict weighted canary splits to GET/HEAD requests (writes always stay on live). Safest for shared-DB splits, but the write path gets no canary signal.'),
        ),
    ]
