# Generated by Django 5.0.14 on 2026-09-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0217_promotion_canary_get_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='promote_canary_sticky',
            field=models.BooleanField(default=False, help_text='Pin canary clients to one variant with a sticky cookie (avoids bouncing stateful sessions between versions). Off by default — plain weighted round-robin.'),
        ),
    ]
