# Generated by Django 5.0.14 on 2026-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0218_promotion_canary_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='rollback_retain_deployments',
            field=models.PositiveIntegerField(default=2, help_text='Successful deployments kept per service for rollback (their images are never deleted by retention)'),
        ),
    ]
