# Generated by Django 5.0.14 on 2026-09-17 23:54

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0219_platformconfig_rollback_retain_deployments'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='provision_mode',
            field=models.CharField(choices=[('container', 'Dedicated container'), ('shared', 'Logical DB on shared server')], default='container', help_text='How this addon is hosted: a dedicated container, or a logical database on the shared Postgres server (new POSTGRES addons default to shared).', max_length=20),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='postgres_shared_addons_default',
            field=models.BooleanField(default=True, help_text='New POSTGRES addons provision as logical databases on the shared server instead of dedicated containers (one server for N addons; Platform HA covers them when the shared instance is replicated). Uncheck to keep per-addon containers.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='shared_postgres_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Superuser password for the shared Postgres addon server (auto-generated on first use).'),
        ),
    ]
