# Generated by Django 5.0.14 on 2026-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0223_addon_pooler_routed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedserver',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
