# Generated by Django 5.0.14 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0229_alter_addon_addon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='build_cpu_quota_percent',
            field=models.PositiveIntegerField(default=400, help_text='Per-build CPU cap in percent of one core (systemd-run CPUQuota; 100 = 1 CPU)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='build_memory_max_mb',
            field=models.PositiveIntegerField(default=10240, help_text='Per-build memory cap for Dockerfile builds (systemd-run MemoryMax)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='build_timeout_seconds',
            field=models.PositiveIntegerField(default=1800, help_text='Cap for a single Docker build before the worker kills it'),
        ),
    ]
