# Generated by Django 5.0.14 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0230_platformconfig_build_caps'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='readiness_path',
            field=models.CharField(blank=True, default='', help_text='Dependency-aware readiness path (e.g. /ready). Probed on green before promotion and required in ongoing checks. Blank = liveness only.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='smoke_command',
            field=models.CharField(blank=True, default='', help_text='Optional post-boot smoke command run inside green via docker exec (e.g. python -c "import app.main"). Non-zero exit blocks promotion. Blank = off.', max_length=500),
        ),
    ]
