# Generated by Django 5.0.14 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0231_service_readiness_smoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('DELETION_PENDING', 'Deletion Pending'), ('DELETION_FAILED', 'Deletion Failed'), ('DELETED', 'Deleted'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=20),
        ),
    ]
