# Generated by Django 5.0.14 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0232_service_status_stopped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='edge_proxy_records',
            field=models.BooleanField(default=True, help_text='Edge Shield: route DNS records through the Cloudflare proxy (Anycast) instead of DNS-only to the origin IP. Absorbs BGP hijack of the origin prefix and L3-L4 DDoS.'),
        ),
    ]
