# Generated by Django 5.0.14 on 2026-09-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0233_edge_proxy_default_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='celery_deploy_max',
            field=models.PositiveIntegerField(default=3, help_text='Deploy worker max concurrency (builds serialize on the fleet lock; extra children serve quick tasks)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='celery_deploy_min',
            field=models.PositiveIntegerField(default=0, help_text='Deploy worker min concurrency (0 = sleep when idle; main worker drains the queue)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='celery_fast_max',
            field=models.PositiveIntegerField(default=2, help_text='Fast worker max concurrency (heartbeats + light I/O scans)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='celery_fast_min',
            field=models.PositiveIntegerField(default=1, help_text='Fast worker min concurrency (0 allowed only if the main worker covers the fast queue)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='celery_main_max',
            field=models.PositiveIntegerField(default=4, help_text='Main worker max concurrency (drains all queues it listens on)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='celery_main_min',
            field=models.PositiveIntegerField(default=0, help_text='Main worker min concurrency (0 = sleep when idle)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='mesh_health_interval',
            field=models.PositiveIntegerField(default=120, help_text='WireGuard mesh health check cadence in seconds (topology freshness only; liveness stays on heartbeats)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='replication_health_interval',
            field=models.PositiveIntegerField(default=60, help_text='Replication lag check cadence in seconds (gauge resolution; failover stays on the 30s addon watchdog)'),
        ),
    ]
