# Generated by Django 5.0.14 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0234_platformconfig_celery_deploy_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='mesh_dns_domain',
            field=models.CharField(blank=True, default='mesh.internal', help_text="DNS zone served by CoreDNS for the WireGuard mesh (e.g. registry.mesh.internal). Empty falls back to MESH_DNS_DOMAIN env, then 'mesh.internal'.", max_length=253),
        ),
    ]
