# Generated by Django 5.0.14 on 2026-09-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0238_service_mesh_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the addon was deprovisioned. Data volume is kept for the retention window (purge task) instead of being removed immediately.', null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='pooler_routed',
            field=models.BooleanField(default=False, help_text='Shared POSTGRES addon dials through the pgbouncer-tenants pooler (set at provision/migration time; sticky — toggling tenant_pooling_enabled never moves it back).'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='retired_volume',
            field=models.CharField(blank=True, default='', help_text='Data volume retained at deprovision; removed by the purge task after the retention window.', max_length=255),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task id running this deployment (for revoke on cancel).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='tenant_pooling_enabled',
            field=models.BooleanField(default=True, help_text='Route NEW shared Postgres addons through the pgbouncer-tenants pooler instead of direct connections. Existing shared addons keep dialling the server directly (sticky).'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mesh_alias',
            field=models.CharField(blank=True, default='', help_text="Stable DNS alias attached to this service's LIVE container on its networks (e.g. 'smsly-marketer' for a service whose container name carries a per-deploy suffix). Lets mesh callers address it without tracking renames. Empty = none.", max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='seed_command',
            field=models.CharField(blank=True, default='', help_text='Optional seed command run inside the live container after promotion (e.g. python manage.py seed_core). Best-effort: failure is logged, never fails the deploy. Blank = off.', max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='seed_last_run',
            field=models.DateTimeField(blank=True, default=None, help_text='Last time the seed command completed (any exit code).', null=True),
        ),
    ]
