# Generated by Django 5.0.14 on 2026-09-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0239_alter_addon_deleted_at_alter_addon_pooler_routed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='addon_type',
            field=models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('MARIADB', 'MariaDB'), ('COCKROACHDB', 'CockroachDB'), ('TIMESCALEDB', 'TimescaleDB'), ('PERCONA', 'Percona Server'), ('VITESS', 'Vitess'), ('MONGODB', 'MongoDB'), ('COUCHDB', 'CouchDB'), ('RETHINKDB', 'RethinkDB'), ('ARANGODB', 'ArangoDB'), ('FERRETDB', 'FerretDB'), ('SURREALDB', 'SurrealDB'), ('REDIS', 'Redis'), ('MEMCACHED', 'Memcached'), ('KEYDB', 'KeyDB'), ('VALKEY', 'Valkey'), ('DRAGONFLYDB', 'DragonflyDB'), ('ETCD', 'etcd'), ('CLICKHOUSE', 'ClickHouse'), ('CASSANDRA', 'Cassandra'), ('SCYLLADB', 'ScyllaDB'), ('NEO4J', 'Neo4j'), ('DGRAPH', 'Dgraph'), ('QDRANT', 'Qdrant'), ('WEAVIATE', 'Weaviate'), ('MILVUS', 'Milvus'), ('CHROMADB', 'ChromaDB'), ('ELASTICSEARCH', 'Elasticsearch'), ('OPENSEARCH', 'OpenSearch'), ('MEILISEARCH', 'MeiliSearch'), ('TYPESENSE', 'Typesense'), ('SOLR', 'Apache Solr'), ('RABBITMQ', 'RabbitMQ'), ('KAFKA', 'Apache Kafka'), ('NATS', 'NATS'), ('REDPANDA', 'Redpanda'), ('PULSAR', 'Apache Pulsar'), ('ACTIVEMQ', 'ActiveMQ'), ('MINIO', 'MinIO'), ('SEAWEEDFS', 'SeaweedFS'), ('INFLUXDB', 'InfluxDB'), ('QUESTDB', 'QuestDB'), ('VICTORIAMETRICS', 'VictoriaMetrics'), ('PROMETHEUS', 'Prometheus'), ('GRAFANA', 'Grafana'), ('JAEGER', 'Jaeger'), ('N8N', 'n8n'), ('TEMPORAL', 'Temporal'), ('VAULT', 'HashiCorp Vault'), ('CONSUL', 'Consul'), ('KEYCLOAK', 'Keycloak'), ('STEEL', 'Steel Browser'), ('BROWSERLESS', 'Browserless Chrome'), ('PGBOUNCER', 'PgBouncer')], max_length=20),
        ),
    ]
