# Generated by Django 5.0.14 on 2026-10-02 02:48

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0240_alter_addon_addon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='cli_config',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='addon',
            name='addon_type',
            field=models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('MARIADB', 'MariaDB'), ('COCKROACHDB', 'CockroachDB'), ('TIMESCALEDB', 'TimescaleDB'), ('PERCONA', 'Percona Server'), ('VITESS', 'Vitess'), ('MONGODB', 'MongoDB'), ('COUCHDB', 'CouchDB'), ('RETHINKDB', 'RethinkDB'), ('ARANGODB', 'ArangoDB'), ('FERRETDB', 'FerretDB'), ('SURREALDB', 'SurrealDB'), ('REDIS', 'Redis'), ('MEMCACHED', 'Memcached'), ('KEYDB', 'KeyDB'), ('VALKEY', 'Valkey'), ('DRAGONFLYDB', 'DragonflyDB'), ('ETCD', 'etcd'), ('CLICKHOUSE', 'ClickHouse'), ('CASSANDRA', 'Cassandra'), ('SCYLLADB', 'ScyllaDB'), ('NEO4J', 'Neo4j'), ('DGRAPH', 'Dgraph'), ('QDRANT', 'Qdrant'), ('WEAVIATE', 'Weaviate'), ('MILVUS', 'Milvus'), ('CHROMADB', 'ChromaDB'), ('ELASTICSEARCH', 'Elasticsearch'), ('OPENSEARCH', 'OpenSearch'), ('MEILISEARCH', 'MeiliSearch'), ('TYPESENSE', 'Typesense'), ('SOLR', 'Apache Solr'), ('RABBITMQ', 'RabbitMQ'), ('KAFKA', 'Apache Kafka'), ('NATS', 'NATS'), ('REDPANDA', 'Redpanda'), ('PULSAR', 'Apache Pulsar'), ('ACTIVEMQ', 'ActiveMQ'), ('MINIO', 'MinIO'), ('SEAWEEDFS', 'SeaweedFS'), ('INFLUXDB', 'InfluxDB'), ('QUESTDB', 'QuestDB'), ('VICTORIAMETRICS', 'VictoriaMetrics'), ('PROMETHEUS', 'Prometheus'), ('GRAFANA', 'Grafana'), ('JAEGER', 'Jaeger'), ('N8N', 'n8n'), ('TEMPORAL', 'Temporal'), ('VAULT', 'HashiCorp Vault'), ('CONSUL', 'Consul'), ('KEYCLOAK', 'Keycloak'), ('STEEL', 'Steel Browser'), ('BROWSERLESS', 'Browserless Chrome'), ('OPENCODE', 'OpenCode CLI'), ('COMMANDCODE', 'CommandCode CLI'), ('ANTIGRAVITYCLI', 'Antigravity CLI'), ('KIMCHI', 'Kimchi CLI'), ('FORGECODE', 'ForgeCode CLI'), ('DEEPAGENTS', 'DeepAgents CLI'), ('QWENCODE', 'Qwen CLI'), ('FACTORYDROID', 'Factory Droid CLI'), ('PGBOUNCER', 'PgBouncer')], max_length=20),
        ),
    ]
