"""URL configuration for Media Node app.

Naming convention: URL names use kebab-case (auto-generated by DRF router).
"""
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_nested import routers

from ..views import (
    AttestationAuditLogViewSet,
    AttestationProfileViewSet,
    MediaCapacityView,
    MediaNodeProfileViewSet,
    MediaParticipantViewSet,
    MediaRoomViewSet,
    MediaWebhookView,
)

router = DefaultRouter()
router.register(r"media-nodes", MediaNodeProfileViewSet, basename="media-node")
router.register(r"attestation", AttestationProfileViewSet, basename="attestation")
router.register(r"attestation-events", AttestationAuditLogViewSet, basename="attestation-event")
router.register(r"capacity", MediaCapacityView, basename="media-capacity")
router.register(r"webhooks", MediaWebhookView, basename="media-webhook")

# Nested: /api/v1/media-nodes/{node_pk}/rooms/
nodes_router = routers.NestedSimpleRouter(router, r"media-nodes", lookup="node")
nodes_router.register(r"rooms", MediaRoomViewSet, basename="media-room")

# Nested: /api/v1/media-nodes/{node_pk}/rooms/{room_pk}/participants/
rooms_router = routers.NestedSimpleRouter(nodes_router, r"rooms", lookup="room")
rooms_router.register(r"participants", MediaParticipantViewSet, basename="media-participant")

urlpatterns = [
    path("", include(router.urls)),
    path("", include(nodes_router.urls)),
    path("", include(rooms_router.urls)),
]
