//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "deployments_deployment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub service_id: Uuid,
    #[sea_orm(column_type = "String(StringLen::N(40))")]
    pub commit_hash: String,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub status: String, // PENDING, BUILDING, RUNNING, FAILED, STOPPED
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub message: Option<String>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub docker_image: Option<String>,
    pub is_rollback: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::service::Entity",
        from = "Column::ServiceId",
        to = "super::service::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Service,
}

impl Related<super::service::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Service.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}