//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "licensing_platformlicense")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub license_key: String,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub tier: String, // community, pro, enterprise
    #[sea_orm(column_type = "Text")]
    pub license_data: String,
    pub is_valid: bool,
    pub last_validated: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub validation_error: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub licensed_to: String,
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub instance_id: String,
    pub expires_at: Option<DateTimeWithTimeZone>,
    pub max_services: i32,
    pub max_team_members: i32,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub payment_provider: String,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub subscription_id: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}