//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "licensing_platformlicense")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "String(StringLen::N(50))")]
    pub tier: String, // COMMUNITY, PRO, ENTERPRISE
    #[sea_orm(column_type = "String(StringLen::N(255))", nullable)]
    pub customer_id: Option<String>, // Stripe/Cryptomus Customer ID
    #[sea_orm(column_type = "String(StringLen::N(255))", nullable)]
    pub subscription_id: Option<String>,
    pub is_active: bool,
    pub expires_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub encrypted_license_key: Option<String>, // Used for offline RSA validation in Enterprise
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}