//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "deployments_service")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project_id: Uuid,
    #[sea_orm(column_type = "String(StringLen::N(100))")]
    pub name: String,
    #[sea_orm(column_type = "String(StringLen::N(120))", unique)]
    pub slug: String,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub deploy_type: String, // GIT, DOCKER, UPLOAD, TEMPLATE
    #[sea_orm(column_type = "String(StringLen::N(200))", nullable)]
    pub repository_url: Option<String>,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub branch: String,
    pub custom_domains: serde_json::Value,
    pub public_domain_hidden: bool,
    #[sea_orm(column_type = "String(StringLen::N(255))")]
    pub root_directory: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Project,
    #[sea_orm(has_many = "super::deployment::Entity")]
    Deployment,
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::deployment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Deployment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}