//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "auth_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "String(StringLen::N(150))", unique)]
    pub username: String,
    #[sea_orm(column_type = "String(StringLen::N(254))")]
    pub email: String,
    #[sea_orm(column_type = "String(StringLen::N(128))")]
    pub password: String,
    pub is_superuser: bool,
    pub is_staff: bool,
    pub is_active: bool,
    pub date_joined: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project::Entity")]
    Project,
    #[sea_orm(has_many = "super::api_key::Entity")]
    APIKey,
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl Related<super::api_key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::APIKey.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}