# Generated by Django 5.0.14 on 2026-07-28 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attestationprofile",
            name="security_level",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="1 = software, 5 = dedicated secure element",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
