# Generated by Django 5.0.14 on 2026-09-02 12:49

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_medianodeinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='medianodeprofile',
            name='script_repo_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Custom scoped token for cloning the scripts repo'),
        ),
        migrations.AddField(
            model_name='medianodeprofile',
            name='script_repo_url',
            field=models.CharField(blank=True, default='', help_text='GitHub or GitLab repo URL for proprietary media scripts', max_length=255),
        ),
    ]
