#!/usr/bin/env bash
# rotate_secrets.sh — generate strong replacements for all .env secrets
#
# Threat model
# ------------
# Treat the working-copy .env as COMPROMISED. Anything that ever touched it
# (laptops, CI runners, backup snapshots, forks of the repo) must be assumed
# to have read the values. The only safe response is to invalidate every
# secret and re-issue it with the upstream provider.
#
# This script does NOT modify the existing .env. It writes a new
# .env.rotated.<timestamp> file that the operator reviews with `diff` and
# then `mv`s into place. The script also tags which values need an
# upstream action (e.g. GitHub webhook secret must be updated on github.com)
# and which do not.
#
# Usage:
#   ./scripts/rotate_secrets.sh [path-to-env-file]
#   # default: .env in the current directory
#
# Output:
#   .env.rotated.<UTC-timestamp>      (mode 0600)

set -euo pipefail

ENV_FILE="${1:-.env}"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
OUT="${ENV_FILE}.rotated.${TS}"

# Generate cryptographically strong secrets
gen_hex() { openssl rand -hex 32; }
gen_base64() { openssl rand -base64 32 | tr -d '\n'; }
gen_token() { python3 -c "import secrets; print(secrets.token_urlsafe(32))"; }

# Read the existing .env (if any) to preserve non-secret values
declare -A PRESERVE
if [ -f "$ENV_FILE" ]; then
    while IFS='=' read -r key value; do
        # Skip comments and blank lines
        [[ -z "$key" || "$key" =~ ^# ]] && continue
        PRESERVE["$key"]="$value"
    done < "$ENV_FILE"
fi

# Required secrets (always rotate)
SECRETS=(
    "SECRET_KEY"
    "FIELD_ENCRYPTION_KEY"        # must be 32-byte url-safe base64 (Fernet)
    "GATEWAY_SECRET"
    "GITHUB_WEBHOOK_SECRET"
    "POSTGRES_PASSWORD"
    "RABBITMQ_PASSWORD"
    "REDIS_PASSWORD"
    "REGISTRY_PASSWORD"
    "GRAFANA_PASSWORD"
    "PGCAT_ADMIN_PASSWORD"
    "AUTOSCALER_API_TOKEN"
    "FRP_AUTH_TOKEN"
)

# Write the rotated file
{
    echo "# SMSLY Hosting — Rotated secrets (${TS})"
    echo "# This file was generated by scripts/rotate_secrets.sh"
    echo "# Review before applying: diff ${ENV_FILE} ${OUT}"
    echo "# Apply: mv ${OUT} ${ENV_FILE}"
    echo ""
    echo "# Upstream actions required after applying this file:"
    echo "#   FIELD_ENCRYPTION_KEY   -> re-encrypt all EncryptedField values (see runbook sec. 8)"
    echo "#   GITHUB_WEBHOOK_SECRET  -> update GitHub repo/org webhook settings"
    echo "#   POSTGRES_PASSWORD      -> align infrastructure/docker/postgres/init-primary.sh, restart db+pgcat+backend"
    echo "#   RABBITMQ_PASSWORD      -> align all broker URLs in compose, restart rabbitmq+celery"
    echo "#   REDIS_PASSWORD         -> align all cache URLs, restart redis+backend+celery"
    echo "#   REGISTRY_PASSWORD      -> regenerate .htpasswd, restart registry, re-login agents"
    echo "#   GRAFANA_PASSWORD       -> notify all dashboard users, restart grafana"
    echo "#   PGCAT_ADMIN_PASSWORD   -> align pgcat.toml, restart pgcat"
    echo "#   AUTOSCALER_API_TOKEN   -> re-issue on every lite/edge agent"
    echo "#   FRP_AUTH_TOKEN         -> re-issue on every FRP client + frps config"
    echo "#   GATEWAY_SECRET         -> restart gateway (no upstream)"
    echo "#   SECRET_KEY             -> restart backend (Django sessions/CSRF invalidated)"
    echo ""

    for key in "${SECRETS[@]}"; do
        case "$key" in
            FIELD_ENCRYPTION_KEY)
                # Fernet requires url-safe base64 of exactly 32 bytes (no padding)
                value="$(python3 -c "import base64,os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")"
                ;;
            *_TOKEN)
                # API tokens: urlsafe token
                value="$(gen_token)"
                ;;
            *)
                # Passwords / symmetric secrets: 32-byte hex
                value="$(gen_hex)"
                ;;
        esac
        echo "${key}=${value}"
    done

    # Preserve non-secret values
    for key in "${!PRESERVE[@]}"; do
        case "$key" in
            POSTGRES_USER|REDIS_HOST|RABBITMQ_HOST|DB_HOST|DOMAIN|ACME_EMAIL|\
            CORS_ALLOWED_ORIGINS|ALLOWED_HOSTS|EMAIL_HOST|EMAIL_PORT|EMAIL_USER|\
            FRP_SERVER_ADDR|FRP_SERVER_PORT)
                echo "${key}=${PRESERVE[$key]}"
                ;;
        esac
    done
} > "$OUT"

chmod 600 "$OUT"

# Verify the new file parses (source it in a subshell to check for syntax errors).
# `set -n` makes bash parse but not execute, which catches any malformed lines.
if ! (set -n; source "$OUT") ; then
    echo "ERROR: rotated file failed parse check: $OUT" >&2
    exit 1
fi

echo "Wrote rotated secrets to: $OUT"
echo "Review with: diff ${ENV_FILE} ${OUT}"
echo "Apply with:  mv ${OUT} ${ENV_FILE}"
