"""Urls module for the global /api/v1/domains/ endpoint.

Naming convention: URL names use kebab-case (auto-generated by DRF router).
"""
from rest_framework.routers import DefaultRouter

from ..views import GlobalDomainViewSet

router = DefaultRouter()
router.register(r'', GlobalDomainViewSet, basename='global-domain')

urlpatterns = router.urls
