//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0

use crate::deployment_status::DeploymentStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

pub use crate::deployment_status::DeploymentStatus as Status;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "deployments_deployment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub service_id: Uuid,
    #[sea_orm(column_type = "String(StringLen::N(40))")]
    pub commit_hash: String,
    #[sea_orm(column_type = "String(StringLen::N(20))")]
    pub status: String, // PENDING, BUILDING, RUNNING, FAILED, STOPPED
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub is_rollback: bool,
    pub requester_id: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::service::Entity",
        from = "Column::ServiceId",
        to = "super::service::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Service,
}

impl Related<super::service::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Service.def()
    }
}

impl Model {
    /// Parse the stored `status` string into the strongly-typed
    /// [`DeploymentStatus`] enum. Returns `None` if the value is not one
    /// of the known states (which would also fail the DB CHECK constraint).
    pub fn status_enum(&self) -> Option<DeploymentStatus> {
        DeploymentStatus::from_str(&self.status)
    }
}

impl ActiveModelBehavior for ActiveModel {}