name: default_ip_remediation
#debug: true
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.GetMeta("http_path") != "/.well-known/acme-challenge/"
decisions:
 - type: ban
   duration: 4h
#on_success: break
---
name: scanner_ip_remediation
#debug: true
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.GetScenario() contains "crowdsecurity/http-probing" && Alert.GetMeta("http_path") != "/.well-known/acme-challenge/"
decisions:
 - type: ban
   duration: 24h
on_success: break
