# Generated by Django 5.0.14 on 2026-02-16 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployments", "0012_apitoken_and_more"),
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domain_instances",
                to="deployments.service",
            ),
        ),
    ]
