# Generated by Django 5.0.14 on 2026-05-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0002_alter_domain_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="dns_actual",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="dns_expected",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dns_pending", "DNS Pending"),
                    ("dns_verified", "DNS Verified"),
                    ("ssl_provisioning", "SSL Provisioning"),
                    ("active", "Active"),
                    ("ssl_failed", "SSL Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
