# Generated by Django 5.0.14 on 2026-06-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_migrate_custom_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_fail_count',
            field=models.IntegerField(default=0),
        ),
    ]
