# Generated by Django 5.0.14 on 2026-09-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0009_add_verify_fail_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='verification_token',
            field=models.CharField(blank=True, default='', help_text='Random per-domain HTTP-proof challenge token (auto-created). Served at /.well-known/smsly-verify/<token> for orange-compatible verification behind Cloudflare proxying.', max_length=64),
        ),
    ]
