# Generated by Django 5.0.14 on 2026-06-18 03:09

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSSO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('SAML', 'SAML 2.0'), ('OIDC', 'OpenID Connect'), ('GOOGLE_WORKSPACE', 'Google Workspace'), ('AZURE_AD', 'Azure AD / Entra ID')], max_length=32)),
                ('label', models.CharField(blank=True, default='', help_text="Display name (e.g. 'Company Okta')", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('oidc_issuer_url', models.URLField(blank=True, default='')),
                ('oidc_client_id', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('oidc_client_secret', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('saml_entity_id', models.URLField(blank=True, default='')),
                ('saml_sso_url', models.URLField(blank=True, default='')),
                ('saml_x509_cert', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('auto_provision_domains', models.JSONField(blank=True, default=list, help_text="Email domains that auto-provision users (e.g. ['company.com'])")),
                ('default_role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', help_text='Role assigned to auto-provisioned users', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization SSO Provider',
                'verbose_name_plural': 'Organization SSO Providers',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
