# Generated by Django 5.0.14 on 2026-06-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_add_organizations_and_sso'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='can_manage_billing',
            field=models.BooleanField(default=False, help_text='Allow this member to manage billing (plans, checkout, invoices)'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, membership automatically expires after this date', null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Suspend membership without removing the record'),
        ),
    ]
